(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("AmazonUIFormExtras"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
(function(p){var r=window.AmazonUIPageJS||window.P,y=r._namespace||r.attributeErrors,g=y?y("AmazonUICalendar"):r;g.guardFatal?g.guardFatal(p)(g,window):g.execute(function(){p(g,window)})})(function(p,r,y){p.when("A").register("a-calendar-utils",function(g){function k(a,c){c=a.getFullYear?a.getMonth()+1:c;a=a.getFullYear?a.getFullYear():a;return l(a,c+1,0).getDate()}function l(a,c,b){var d=null;a&&(d=a.getFullYear?new Date(a.getTime()):void 0!==a.year&&void 0!==a.month&&void 0!==a.day?new Date(a.year,
a.month-1,a.day):new Date(a,c-1,b));return d}function e(a){var c=a.match(/[.\/\-\s].*?/);a=a.split(/\W+/);if(!c||!a||0===a.length)throw Error("Invalid date format.");return{separator:c,parts:a}}return{numDaysInMonth:k,newDate:l,add:function(a,c,b){if("d"===b||"w"===b)a.setDate(a.getDate()+c*("w"===b?7:1));else{var d=a.getFullYear()+("y"===b?c:0);c=a.getMonth()+("m"===b?c:0);a.setTime(l(d,c+1,Math.min(a.getDate(),k(d,c+1))).getTime())}return a},parseDate:function(a,c){c=e(c);a=a?a.split(c.separator):
[];var b=null,d;if(a.length===c.parts.length){d=new Date;for(var u=d.getFullYear(),f=d.getDate(),m=d.getMonth(),n=0;n<c.parts.length;n++)switch(d=parseInt(a[n],10),c.parts[n]){case "dd":case "d":f=d;break;case "mm":case "m":m=d-1;break;case "yy":case "yyyy":u=100>d?40>d?2E3+d:1900+d:d}!isNaN(u)&&0<=m&&11>=m&&1<=f&&f<=k(u,m+1)&&(b=new Date(u,m,f,0,0,0))}return b},formatDate:function(a,c){c=e(c);a={d:a.getDate(),m:a.getMonth()+1,yyyy:a.getFullYear()};a.dd=(10>a.d?"0":"")+a.d;a.mm=(10>a.m?"0":"")+a.m;
for(var b=[],d=0,u=c.parts.length;d<u;d++)b.push(a[c.parts[d]]);return b.join(c.separator)}}});"use strict";p.when("A").register("a-calendar-template-default",function(g){return{monthNames:"January February March April May June July August September October November December".split(" "),monthNamesShort:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),dayNames:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),dayNamesShort:"Sun Mon Tue Wed Thu Fri Sat".split(" "),dayNamesMin:"Su Mo Tu We Th Fr Sa".split(" "),
firstDay:0,currentFormat:"{{month}} {{year}}",genericStatus:"Show {{month}} {{year}}",prevText:"\x26lt;Prev",prevStatus:"Show the previous month",prevJumpText:"\x26lt;\x26lt;",prevJumpStatus:"Show the previous year",nextText:"Next\x26gt;",nextStatus:"Show the next month",nextJumpText:"\x26gt;\x26gt;",nextJumpStatus:"Show the next year",currentText:"Current",currentStatus:"Show the current month",todayText:"Today",todayStatus:"Show today's month",clearText:"Clear",clearStatus:"Clear all the dates",
closeText:"Close",closeStatus:"Close the calendar",yearStatus:"Change the year",monthStatus:"Change the month",weekText:"Wk",weekStatus:"Week of the year",dayStatus:"Select DD, M d, yyyy",dateFormat:"mm/dd/yyyy",dateFormatDescription:"Date with format m m/d d/y y y y",defaultStatus:"Select a date",isRTL:!1}});"use strict";p.when("A","a-calendar-utils","a-calendar-template-default").register("a-calendar-renderer",function(g,k,l){function e(b){if(0!==arguments.length)return this.templateData=b||l,this}
var a=g.$,c=e.prototype;c.notifyChange=function(b,d){for(var a=this,f=b.attributes,c=b.$container,n=[],e=k.newDate(f.viewedYear,f.viewedMonth,1),h=0;h<f.numViewMonths;h++){var t=e.getMonth()+1,l=e.getFullYear();n.push(a.renderMonth(f,l,t,0===h,h===f.numViewMonths-1));e=k.add(e,1,"m")}g.delay(function(){c.html(n.join(""));a.notifyBlacklistChange(b);d&&d();g.trigger("a:calendar:change:"+b.attributes.id)},0)};c.renderMonth=function(b,d,a,f,c){var n=this.templateData,e=k.numDaysInMonth(d,a),h=n.firstDay,
t=k.newDate(d,a,1).getDay(),g=k.newDate(d,a,1).getTime(),l=k.newDate(d,a+1,0).getTime(),p=b.minDate?b.minDate.getTime():null,x=b.maxDate?b.maxDate.getTime():null,q=k.newDate(d,a,1),v=(t-h+7)%7,t=42-v-e,r=b.selectedDate?b.selectedDate.getTime():null;k.add(q,-v,"d");for(var h=[],w=0;w<v;w++)h.push(this.renderDayOutsideMonth(q)),k.add(q,1,"d");for(v=0;v<e;v++)w=q.getTime(),h.push(this.renderDay(q,b.selectedDate&&w===r,x&&w>x||p&&w<p,b.onRenderDayClass)),k.add(q,1,"d");for(b=0;b<t;b++)h.push(this.renderDayOutsideMonth(q)),
k.add(q,1,"d");for(b=1;b<=h.length;b++)q=b-1,1===b?h[q]="\x3ctr\x3e"+h[q]:b===h.length?h[q]+="\x3c/tr\x3e":0===b%7&&(h[q]+="\x3c/tr\x3e\x3ctr\x3e");c=this.renderMonthHeader(d,a,f&&(!p||g>p),c&&(!x||l<x));g=this.renderDayHeader();l=n.currentFormat;l=l.replace("{{month}}",n.monthNames[(a-1+12)%12]).replace("{{year}}",d);d=["\x3cdiv class\x3d'a-cal-month-container",f?" a-cal-month-container-first":"","'\x3e",c,"\x3ctable class\x3d'a-cal-month-table' summary\x3d'",l,"'\x3e",g,"\x3ctbody class\x3d'a-cal-days'\x3e"].concat(h);
d.push("\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e");return d.join("")};c.renderDay=function(a,d,c,f){var m=a.getTime();f=["a-cal-d"," ",d?"a-cal-select ":"",c?"a-cal-outbound ":"",f?f.call(this,a)+" ":"","a-cal-d-",m];return["\x3ctd class\x3d'"].concat(f).concat(["' data-timestamp\x3d'",m,"'\x3e\x3ca href\x3d'javascript:void(0)' class\x3d'a-declarative a-cal-date-anchor' data-action\x3d'a-cal-select-date' aria-disabled\x3d'",c?"true":"false","' aria-selected\x3d'",d?"true":"false","'\x3e",a.getDate(),
"\x3c/a\x3e\x3c/td\x3e"]).join("")};c.renderDayOutsideMonth=function(a){return["\x3ctd class\x3d'a-cal-na a-cal-d-",a.getTime(),"'\x3e",this.templateData.dayOutsideMonth,"\x3c/td\x3e"].join("")};c.renderDayHeader=function(){for(var a=this.templateData,d=[],c=0;7>c;c++){var f=(c+a.firstDay)%7;d.push("\x3cth class\x3d'a-cal-day-label'\x3e");d.push(a.dayNamesShort[f]);d.push("\x3c/th\x3e")}a=["\x3cthead class\x3d'a-cal-labels'\x3e\x3ctr\x3e"].concat(d);a.push("\x3c/tr\x3e\x3c/thead\x3e");return a.join("")};
c.renderMonthHeader=function(a,d,c,f){var m=this.templateData,n=m.monthNames[(d-1+12)%12],e=m.monthNames[(d+12)%12],h=1===d?a-1:a,t=12===d?a+1:a,k=m.genericStatus,g=m.genericStatus,l=m.currentFormat,k=k.replace("{{month}}",m.monthNames[(d-2+12)%12]).replace("{{year}}",h),g=g.replace("{{month}}",e).replace("{{year}}",t),l=l.replace("{{month}}",n).replace("{{year}}",a);a=c?["\x3ca class\x3d'a-declarative a-cal-paginate-prev' data-action\x3d'a-cal-prev-month' tabindex\x3d'0'\x3e\x3cspan class\x3d'a-offscreen'\x3e",
k,"\x3c/span\x3e\x3ci class\x3d'a-icon a-icon-previous'\x3e\x3c/i\x3e\x3c/a\x3e"].join(""):"";f=f?["\x3ca class\x3d'a-declarative a-cal-paginate-next' data-action\x3d'a-cal-next-month' tabindex\x3d'0'\x3e\x3cspan class\x3d'a-offscreen'\x3e",g,"\x3c/span\x3e\x3ci class\x3d'a-icon a-icon-next'\x3e\x3c/i\x3e\x3c/a\x3e"].join(""):"";return["\x3cdiv class\x3d'a-row a-cal-month-row'\x3e\x3cdiv class\x3d'a-column a-span2'\x3e",a,"\x3c/div\x3e\x3cdiv class\x3d'a-column a-span8 a-text-center'\x3e\x3ch4 class\x3d'a-cal-month-header' tabindex\x3d'0'\x3e",
l,"\x3c/h4\x3e\x3c/div\x3e\x3cdiv class\x3d'a-column a-span2 a-span-last'\x3e",f,"\x3c/div\x3e\x3c/div\x3e"].join("")};c.notifyInputChange=function(a){var d=a.attributes.$inputContainer,c=a.attributes.calInput;if(d){a=a.attributes.selectedDate;d.find(".a-cal-input");var f,m,n;a&&(f=a.getMonth()+1,m=a.getDate(),n=a.getFullYear());d.find(".a-cal-select-month").val(f);d.find(".a-cal-select-day").val(m);d.find(".a-cal-select-year").val(n);c&&c.setDate(a)}};c.notifyDaySelection=function(a,d,c){a=a.$container.find(".a-cal-d.a-cal-d-"+
d.getTime());d=a.find("a");a.toggleClass("a-cal-select",c);d.attr("aria-selected",c)};c.notifyBlacklistChange=function(c){var d=c.$container,e=c.attributes.dateBlacklisted;e?d.find(".a-cal-d").each(function(d,c){d=a(c);var b=e(new Date(d.data("timestamp")));d.attr("aria-disabled",function(){return b?"true":"false"}).toggleClass("a-cal-inactive",b)}):d.find(".a-cal-d").removeClass("a-cal-inactive")};return e});"use strict";p.when("A","a-calendar-utils","a-calendar-renderer-instance","a-calendar-input").register("a-calendar",
function(g,k,l,e){function a(a,b){if(0!==arguments.length){b=b||{};this.$container=a;this.observer=b.observer||l;var f=this.attributes={numViewMonths:1};g.extend(f,b);f.selectedDate=k.newDate(f.selectedDate);f.minDate=k.newDate(f.minDate);f.maxDate=k.newDate(f.maxDate);var m=this.attributes.selectedDate||new Date;f.hasOwnProperty("viewedMonth")||(f.viewedMonth=m.getMonth()+1);f.hasOwnProperty("viewedYear")||(f.viewedYear=m.getFullYear());m=this.getTemplateData();if(f.$inputContainer&&m){var n=f.$inputContainer.find(".a-cal-input");
n.attr("aria-label",m.dateFormatDescription);f.calInput=new e(n,this,m.dateFormat)}f.id||(f.id=++c);this.observer.notifyChange(this);this.observer.notifyInputChange(this);return this}}var c=0,b=a.prototype;b.getTemplateData=function(){return this.observer?this.observer.templateData:null};b.selectDate=function(a,c,f){var b=this.attributes;if(!b.disabled){var e=k.newDate(a,c,f);if(!e||!isNaN(e.getFullYear())){var g=b.dateBlacklisted,h=b.minDate,t=b.maxDate;e&&(g&&g(a,c,f)||h&&e.getTime()<h.getTime()||
t&&e.getTime()>t.getTime())?b.onSelectInactiveDate&&b.onSelectInactiveDate.call(this,a,c,f):(g=this.observer,h=k.newDate(b.selectedDate),b.selectedDate=e,h&&g.notifyDaySelection(this,h,!1),b.selectedDate&&g.notifyDaySelection(this,b.selectedDate,!0),b.onSelectDate&&b.onSelectDate.call(this,a,c,f),b.selectedDate&&(a=b.viewedYear,c=b.viewedMonth,e=b.numViewMonths,f=(new Date(a,c-1,1)).getTime(),a=(new Date(a,c-1+e,0)).getTime(),c=b.selectedDate.getTime(),c<f||c>a)&&(this.changeViewedYear(b.selectedDate.getFullYear()),
this.changeViewedMonth(b.selectedDate.getMonth()+1)),this.observer.notifyInputChange(this))}}};b.changeViewedMonth=function(a){var c=this,b=c.attributes;if(!b.disabled){var e=b.minDate,g=b.maxDate,l=b.viewedYear,h=k.newDate(l,a,1),l=k.newDate(l,a+1,0);e&&l.getTime()<e.getTime()||g&&h.getTime()>g.getTime()?b.onChangeViewedMonthFail&&b.onChangeViewedMonthFail.call(c,a):(b.viewedMonth=h.getMonth()+1,b.viewedYear=h.getFullYear(),c.observer.notifyChange(c,function(){b.onChangeViewedMonth&&b.onChangeViewedMonth.call(c,
a)}))}};b.changeViewedYear=function(a){var c=this,b=c.attributes;if(!b.disabled){var e=b.minDate,g=b.maxDate,l=b.viewedMonth,h=k.newDate(a,l,1),l=k.newDate(a,l+1,0);e&&l.getTime()<e.getTime()||g&&h.getTime()>g.getTime()?b.onChangeViewedYearFail&&b.onChangeViewedYearFail.call(c,a):(b.viewedMonth=h.getMonth()+1,b.viewedYear=h.getFullYear(),c.observer.notifyChange(c,function(){b.onChangeViewedYear&&b.onChangeViewedYear.call(c,a)}))}};b.changeDateBlacklisted=function(a){this.attributes.disabled||(this.attributes.dateBlacklisted=
a,this.observer.notifyBlacklistChange(this),this.attributes.onChangeDateBlacklisted&&this.attributes.onChangeDateBlacklisted.call(this,a))};b.setDisabled=function(a){this.attributes.disabled=a};return a});"use strict";p.when("A","a-calendar","a-calendar-renderer-instance","a-popover").register("a-calendar-framework",function(g,k,l,e){function a(a,c){a.jquery||(a=n(a));c=new k(a,c);r[c.attributes.id]=c;a.data("a-cal-id",c.attributes.id).addClass("a-cal-calendar-container").removeClass("a-cal-static");
return c}function c(c,b){b=g.extend({activate:"onclick"},b||{});b=a(n("\x3cdiv /\x3e"),b);c.data("a-cal-id",b.attributes.id).data("a-cal-popover",!0).removeClass("a-cal-static");return b}function b(a,b){b=b||{};b.$inputContainer=a;b=c(a.find(".a-cal-input"),b);a.find(".a-cal-input-container").removeClass("a-hidden");a.find(".a-cal-dropdown-container").addClass("a-hidden").attr("aria-hidden","true");a.data("a-cal-id",b.attributes.id).data("a-cal-input",!0).addClass("a-cal-calendar-container").removeClass("a-cal-static");
return b}function d(c,b){b=b||{};b.$inputContainer=c;b=a(n("\x3cdiv class\x3d'a-row a-cal-calendar-container' /\x3e"),b);c.append(b.$container);c.find(".a-cal-dropdown-container").addClass("a-hidden").attr("aria-hidden","true");c.data("a-cal-id",b.attributes.id).data("a-cal-input",!0).addClass("a-cal-calendar-container").removeClass("a-cal-static");return b}function u(h){h.jquery||(h=n(h));var e=h.data("a-cal-attributes")||{},f=h.data("a-cal-popover"),k=h.data("a-cal-input"),l=h.data("a-cal-inline"),
m=h.data("a-cal-renderer-instance")||"a-calendar-renderer-instance";p.when(m).execute(function(m){m=g.extend({observer:m},e);k?l?d(h,m):b(h,m):f?c(h,m):a(h,m)})}function f(){n(".a-cal-static").each(function(){u(n(this))})}function m(a){var b;a.jquery||(a=n(a));a.length&&(b=a.closest(".a-cal-calendar-container"),b=b.length?r[b.data("a-cal-id")]:r[a.data("a-cal-id")]);return b}var n=g.$,r={};g.on("a:pageUpdate ready",f);g.declarative("a-cal-input",["click","keyup"],function(a){if(("keyup"===a.type&&
a.$event.keyCode===g.constants.keycodes.ENTER||"click"===a.type)&&!e.get(a.$target)){var b=a.$target.data("a-cal-id"),b=r[b];e.create(a.$target,{activate:"onclick",focusWhenShown:!1,width:"auto",padding:"none",position:b.attributes.position?b.attributes.position:"triggerBottom",closeButton:!1,popoverArrow:!1}).update({content:b.$container.addClass("a-cal-in-popover")}).show()}});return{create:a,createWithPopover:c,createWithInput:b,createWithInputInline:d,createAll:f,get:m,getById:function(a){return r[a]},
remove:function(a){var b=m(a);if(b){var c=b.attributes.$inputContainer;b.$container.remove();delete r[b.attributes.id];a.data("a-cal-popover")&&e.remove(a);c&&(a=c.find(".a-popover-trigger"),a.data("a-cal-popover")&&e.remove(a))}}}});"use strict";p.when("A","a-calendar-framework","a-popover").register("a-calendar-handler",function(g,k,l){var e=g.$;g.declarative("a-cal-select-date",["click"],function(a){var c=a.$target;if(a=k.get(c))c=new Date(c.parent().data("timestamp")||c.data("timestamp")),a.selectDate(c),
a.attributes.$inputContainer&&(a=l.get(a.attributes.$inputContainer.find(".a-cal-input")))&&a.hide()});g.declarative("a-cal-dropdown-select",["change"],function(a){if(a=k.get(a.$target)){var c=a.attributes.$inputContainer;if(c){var b=c.find(".a-cal-select-year").val(),d=c.find(".a-cal-select-month").val(),c=c.find(".a-cal-select-day").val();b&&d&&c&&a.selectDate(b,d,c)}}});g.declarative("a-cal-prev-month",["click"],function(a){var c=k.get(a.$target);c&&c.changeViewedMonth(c.attributes.viewedMonth-
1);e(a.target).focus()});g.declarative("a-cal-next-month",["click"],function(a){var c=k.get(a.$target);c&&c.changeViewedMonth(c.attributes.viewedMonth+1);e(a.target).focus()});e(document).delegate(".a-icon-calendar","click",function(a){a.stopImmediatePropagation();e(a.target).parent().siblings(".a-cal-input").focus().click();e("html").hasClass("a-ie8")&&e(a.target).addClass("a-hey-ie8").removeClass("a-hey-ie8")});e(document).delegate(".a-cal-input","focusin",function(a){e(a.target).siblings(".a-icon-calendar").addClass("a-icon-calendar-focus")}).delegate(".a-cal-input",
"focusout",function(a){e(a.target).siblings(".a-icon-calendar").removeClass("a-icon-calendar-focus")})});"use strict";p.when("A","a-calendar-renderer","a-calendar-template-default").register("a-calendar-renderer-instance",function(g,k,l){return new k(l)});"use strict";p.when("A","a-calendar-utils").register("a-calendar-input",function(g,k){function l(e,a,c){var b=this;b.$input=e;b.format=c;b.curDate=k.parseDate(e.val(),c);b.$input.bind("keyup change",function(){b.curDate=k.parseDate(e.val(),c);a.selectDate(b.curDate)}).bind("focusout",
function(){b.setDate(a.attributes.selectedDate,!0)})}l.prototype.setDate=function(e,a){var c=this.curDate,b=c instanceof Date,d=e instanceof Date,g=b&&d;if(!e||d)if(b=!g&&(b||d),g&&c.getTime()!==e.getTime()||g&&!0===a||b)e=(this.curDate=e)?k.formatDate(e,this.format):null,this.$input.val(e)};return l})});
/* ******** */
