(function(f){var k=window.AmazonUIPageJS||window.P,q=k._namespace||k.attributeErrors,b=q?q("CustomerReviewsVotingAssets"):k;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,k,q){f.when("A","vote-model","vote-view").register("vote-controller",function(b,a,d){function e(a){d.hideButtons(a);d.showFeedback(a)}function g(b,g){e(b);a.submitVote(g.ajaxUrl,g.voteValue,g.voteInstanceId,g.csrfT,function(a){!0===a?(d.hideFeedback(b),d.showThankYouAlert(b)):(d.hideFeedback(b),
d.showErrorAlert(b))},function(){d.hideFeedback(b);d.showErrorAlert(b)})}b.declarative("reviews:vote-action","click",function(a){g(a.$target,a.data);a.$event.preventDefault()});return{submitVote:g}});f.when("A","cr-ajax-model").register("vote-model",function(b,a){return{submitVote:function(b,e,g,c,f,k){a.post(b,{params:{voteInstanceId:g,voteValue:e,csrfT:c},attribution:"submitVote",success:f,error:k})}}});f.when("A").register("vote-view",function(b){function a(a,b){return a.closest(".cr-vote").find(b)}
return{hideThankYouAlert:function(b){a(b,".cr-vote-success").addClass("aok-hidden")},showThankYouAlert:function(b){a(b,".cr-vote-success").removeClass("aok-hidden")},showErrorAlert:function(b){a(b,".cr-vote-error").removeClass("aok-hidden")},showFeedback:function(b){a(b,".cr-vote-feedback").removeClass("aok-hidden")},hideFeedback:function(b){a(b,".cr-vote-feedback").addClass("aok-hidden")},hideButtons:function(b){a(b,".cr-vote-buttons").addClass("aok-hidden")}}})});
/* ******** */
(function(f){var k=window.AmazonUIPageJS||window.P,q=k._namespace||k.attributeErrors,b=q?q("CustomerReviewsGalleryAssets"):k;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,k,q){f.when("A","load").register("review-image-asset-loader",function(b){var a=!1;b.ajax("/gp/customer-reviews/aj/private/reviewsGallery/get-image-gallery-assets",{method:"post",success:function(b){f.load.css(b.reviewsLightboxCSS);f.load.js(b.reviewsLightboxJS);a=!0;f.register("review-image-assets-loaded",
{})},error:function(){var a;a="/gp/customer-reviews/aj/metrics/log-values?noCache="+(new Date).getTime();a+="&SimpleStack:ReviewImageAssetLoaderFailure=1";k.Image&&((new Image).src=a)}});return{isLoaded:function(){return a}}});f.when("A","jQuery","cr-log-utils","review-image-assets-loaded").register("review-image-binder",function(b,a,d){function e(b,c,e,n,k){if(!(b&&c&&e instanceof a&&n instanceof a&&k instanceof a))return d.logError("Invalid parameters for imageBinder.initializeForAsin with ASIN: "+
b+", galleryName: "+c+", $popoverTrigger: "+e+", $thumbnails: "+n+", $galleryLink: "+k,"FATAL"),!1;(new ReviewsLightbox(c,"DESKTOP")).initializeForAsin(b);var p="reviewsLightbox-ready-"+c;n.click(function(){var b=n.index(this);e.click();f.when(p).execute(function(){a("#"+c).trigger("jumpToImageAtIndex",b)})});k.click(function(){e.click();f.when(p).execute(function(){a("#"+c).trigger("hideImmersiveView")})});return!0}f.when("reviewsLightbox-js").execute(function(){var b=a("#reviews-image-gallery-container"),
c=b.attr("data-asin");0<b.length&&c&&e(c,"reviews-image-gallery",b.find(".a-popover-trigger"),b.find(".review-image-tile"),b.find("#reviews-image-gallery-link"))});return{bindReview:function(b,c,d){var e=new ReviewGallery(d,"DESKTOP");e.initializeForReview(b);var k=a("#"+c);k.find(".review-image-tile").each(function(b){a(this).click(function(){k.find(".a-popover-trigger").click();f.when("reviewsLightbox-ready-"+d).execute(function(){e.render();e.showImageAtIndex(b)})})})},initializeForAsin:e}});
f.when("A","jQuery","cr-video-model","cr-video-view","reviews-constants").register("cr-video-controller",function(b,a,d,e,g){function c(){b.each(a(".review-views .review"),function(a,b){if(a&&a.id){var c=d.getEmbedInfo(a.id);c&&e.embedVideo(c)}})}b.on(g.events.RELOAD_COMPLETE,function(){c()});c();return{initAll:c}});f.when("jQuery").register("cr-video-model",function(b){return{getEmbedInfo:function(a){var d="video-block-"+a,e=b("#"+a+" .video-url").val(),g=b("#"+a+" .video-slate-img-url").val(),
c=b("#cr-video-swf-url").val();return a&&e&&c?{videoDomId:d,videoUrl:e,videoSlateImgUrl:g,videoSwfUrl:c}:!1}}});f.when("jQuery","afterLoad").register("cr-video-view",function(b){f.now("Airy").execute(function(a){var d=b("#cr-airy-js-source-url").val(),e=b("#cr-airy-css-source-url").val();a||"string"!==typeof d||"string"!==typeof e||(f.load.js(d),f.load.css(e))});return{embedVideo:function(a){f.when("Airy").execute(function(b){b.embed({parentId:a.videoDomId,streamingUrls:[a.videoUrl],
slateImages:{preloadSlate:a.videoSlateImgUrl},swfUrl:a.videoSwfUrl})})}}})});
/* ******** */
