(function(e,j,X){e.execute(function(){e.register("SWFObject",function(){var e=function(){function n(){if(!E){try{var c=h.getElementsByTagName("body")[0].appendChild(h.createElement("span"));c.parentNode.removeChild(c)}catch(i){return}E=!0;for(var c=K.length,B=0;B<c;B++)K[B]()}}function y(c){E?c():K[K.length]=c}function J(c){if(typeof o.addEventListener!=m)o.addEventListener("load",c,!1);else if(typeof h.addEventListener!=m)h.addEventListener("load",c,!1);else if(typeof o.attachEvent!=m)k(o,"onload",
c);else if(typeof o.onload=="function"){var i=o.onload;o.onload=function(){i();c()}}else o.onload=c}function H(){var c=h.getElementsByTagName("body")[0],i=h.createElement(z);i.setAttribute("type",L);var B=c.appendChild(i);if(B){var a=0;(function(){if(typeof B.GetVariable!=m){var d=B.GetVariable("$version");if(d)d=d.split(" ")[1].split(","),g.pv=[parseInt(d[0],10),parseInt(d[1],10),parseInt(d[2],10)]}else if(a<10){a++;setTimeout(arguments.callee,10);return}c.removeChild(i);B=null;u()})()}else u()}
function u(){var c=C.length;if(c>0)for(var i=0;i<c;i++){var a=C[i].id,q=C[i].callbackFn,b={success:!1,id:a};if(g.pv[0]>0){var h=d(a);if(h)if(v(C[i].swfVersion)&&!(g.wk&&g.wk<312)){if(F(a,!0),q)b.success=!0,b.ref=s(a),q(b)}else if(C[i].expressInstall&&t()){b={};b.data=C[i].expressInstall;b.width=h.getAttribute("width")||"0";b.height=h.getAttribute("height")||"0";if(h.getAttribute("class"))b.styleclass=h.getAttribute("class");if(h.getAttribute("align"))b.align=h.getAttribute("align");for(var l={},h=
h.getElementsByTagName("param"),f=h.length,e=0;e<f;e++)h[e].getAttribute("name").toLowerCase()!="movie"&&(l[h[e].getAttribute("name")]=h[e].getAttribute("value"));w(b,l,a,q)}else r(h),q&&q(b)}else if(F(a,!0),q){if((a=s(a))&&typeof a.SetVariable!=m)b.success=!0,b.ref=a;q(b)}}}function s(c){var i=null;if((c=d(c))&&c.nodeName=="OBJECT")typeof c.SetVariable!=m?i=c:(c=c.getElementsByTagName(z)[0])&&(i=c);return i}function t(){return!M&&v("6.0.65")&&(g.win||g.mac)&&!(g.wk&&g.wk<312)}function w(c,i,a,q){M=
!0;P=q||null;S={success:!1,id:a};var e=d(a);if(e){e.nodeName=="OBJECT"?(I=f(e),N=null):(I=e,N=a);c.id=T;if(typeof c.width==m||!/%$/.test(c.width)&&parseInt(c.width,10)<310)c.width="310";if(typeof c.height==m||!/%$/.test(c.height)&&parseInt(c.height,10)<137)c.height="137";h.title=h.title.slice(0,47)+" - Flash Player Installation";q=g.ie&&g.win?"ActiveX":"PlugIn";q="MMredirectURL="+o.location.toString().replace(/&/g,"%26")+"&MMplayerType="+q+"&MMdoctitle="+h.title;typeof i.flashvars!=m?i.flashvars+=
"&"+q:i.flashvars=q;if(g.ie&&g.win&&e.readyState!=4)q=h.createElement("div"),a+="SWFObjectNew",q.setAttribute("id",a),e.parentNode.insertBefore(q,e),e.style.display="none",function(){e.readyState==4?e.parentNode.removeChild(e):setTimeout(arguments.callee,10)}();b(c,i,a)}}function r(c){if(g.ie&&g.win&&c.readyState!=4){var i=h.createElement("div");c.parentNode.insertBefore(i,c);i.parentNode.replaceChild(f(c),i);c.style.display="none";(function(){c.readyState==4?c.parentNode.removeChild(c):setTimeout(arguments.callee,
10)})()}else c.parentNode.replaceChild(f(c),c)}function f(c){var i=h.createElement("div");if(g.win&&g.ie)i.innerHTML=c.innerHTML;else if(c=c.getElementsByTagName(z)[0])if(c=c.childNodes)for(var a=c.length,d=0;d<a;d++)!(c[d].nodeType==1&&c[d].nodeName=="PARAM")&&c[d].nodeType!=8&&i.appendChild(c[d].cloneNode(!0));return i}function b(c,i,a){var b,e=d(a);if(g.wk&&g.wk<312)return b;if(e){if(typeof c.id==m)c.id=a;if(g.ie&&g.win){var f="",l;for(l in c)if(c[l]!=Object.prototype[l])l.toLowerCase()=="data"?
i.movie=c[l]:l.toLowerCase()=="styleclass"?f+=' class="'+c[l]+'"':l.toLowerCase()!="classid"&&(f+=" "+l+'="'+c[l]+'"');l="";for(var x in i)i[x]!=Object.prototype[x]&&(l+='<param name="'+x+'" value="'+i[x]+'" />');e.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+f+">"+l+"</object>";O[O.length]=c.id;b=d(c.id)}else{x=h.createElement(z);x.setAttribute("type",L);for(var j in c)c[j]!=Object.prototype[j]&&(j.toLowerCase()=="styleclass"?x.setAttribute("class",c[j]):j.toLowerCase()!=
"classid"&&x.setAttribute(j,c[j]));for(f in i)i[f]!=Object.prototype[f]&&f.toLowerCase()!="movie"&&(c=x,l=f,j=i[f],a=h.createElement("param"),a.setAttribute("name",l),a.setAttribute("value",j),c.appendChild(a));e.parentNode.replaceChild(x,e);b=x}}return b}function a(c){var a=d(c);if(a&&a.nodeName=="OBJECT")g.ie&&g.win?(a.style.display="none",function(){if(a.readyState==4){var b=d(c);if(b){for(var e in b)typeof b[e]=="function"&&(b[e]=null);b.parentNode.removeChild(b)}}else setTimeout(arguments.callee,
10)}()):a.parentNode.removeChild(a)}function d(c){var a=null;try{a=h.getElementById(c)}catch(b){}return a}function k(c,a,b){c.attachEvent(a,b);G[G.length]=[c,a,b]}function v(c){var a=g.pv,c=c.split(".");c[0]=parseInt(c[0],10);c[1]=parseInt(c[1],10)||0;c[2]=parseInt(c[2],10)||0;return a[0]>c[0]||a[0]==c[0]&&a[1]>c[1]||a[0]==c[0]&&a[1]==c[1]&&a[2]>=c[2]?!0:!1}function R(c,a,b,d){if(!g.ie||!g.mac){var e=h.getElementsByTagName("head")[0];if(e){b=b&&typeof b=="string"?b:"screen";d&&(Q=A=null);if(!A||Q!=
b)d=h.createElement("style"),d.setAttribute("type","text/css"),d.setAttribute("media",b),A=e.appendChild(d),g.ie&&g.win&&typeof h.styleSheets!=m&&h.styleSheets.length>0&&(A=h.styleSheets[h.styleSheets.length-1]),Q=b;g.ie&&g.win?A&&typeof A.addRule==z&&A.addRule(c,a):A&&typeof h.createTextNode!=m&&A.appendChild(h.createTextNode(c+" {"+a+"}"))}}}function F(c,a){if(U){var b=a?"visible":"hidden";E&&d(c)?d(c).style.visibility=b:R("#"+c,"visibility:"+b)}}function V(c){return/[\\\"<>\.;]/.exec(c)!=null&&
typeof encodeURIComponent!=m?encodeURIComponent(c):c}var m="undefined",z="object",L="application/x-shockwave-flash",T="SWFObjectExprInst",o=j,h=document,D=navigator,W=!1,K=[function(){W?H():u()}],C=[],O=[],G=[],I,N,P,S,E=!1,M=!1,A,Q,U=!0,g=function(){var c=typeof h.getElementById!=m&&typeof h.getElementsByTagName!=m&&typeof h.createElement!=m,a=D.userAgent.toLowerCase(),b=D.platform.toLowerCase(),d=b?/win/.test(b):/win/.test(a),b=b?/mac/.test(b):/mac/.test(a),a=/webkit/.test(a)?parseFloat(a.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,
"$1")):!1,e=!+"1",g=[0,0,0],f=null;if(typeof D.plugins!=m&&typeof D.plugins["Shockwave Flash"]==z){if((f=D.plugins["Shockwave Flash"].description)&&!(typeof D.mimeTypes!=m&&D.mimeTypes[L]&&!D.mimeTypes[L].enabledPlugin))W=!0,e=!1,f=f.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),g[0]=parseInt(f.replace(/^(.*)\..*$/,"$1"),10),g[1]=parseInt(f.replace(/^.*\.(.*)\s.*$/,"$1"),10),g[2]=/[a-zA-Z]/.test(f)?parseInt(f.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof o.ActiveXObject!=m)try{var j=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");
if(j&&(f=j.GetVariable("$version")))e=!0,f=f.split(" ")[1].split(","),g=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)]}catch(k){}return{w3:c,pv:g,wk:a,ie:e,win:d,mac:b}}();(function(){g.w3&&((typeof h.readyState!=m&&h.readyState=="complete"||typeof h.readyState==m&&(h.getElementsByTagName("body")[0]||h.body))&&n(),E||(typeof h.addEventListener!=m&&h.addEventListener("DOMContentLoaded",n,!1),g.ie&&g.win&&(h.attachEvent("onreadystatechange",function(){h.readyState=="complete"&&(h.detachEvent("onreadystatechange",
arguments.callee),n())}),o==top&&function(){if(!E){try{h.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}n()}}()),g.wk&&function(){E||(/loaded|complete/.test(h.readyState)?n():setTimeout(arguments.callee,0))}(),J(n)))})();(function(){g.ie&&g.win&&j.attachEvent("onunload",function(){for(var c=G.length,b=0;b<c;b++)G[b][0].detachEvent(G[b][1],G[b][2]);c=O.length;for(b=0;b<c;b++)a(O[b]);for(var d in g)g[d]=null;g=null;for(var f in e)e[f]=null;e=null})})();return{registerObject:function(a,
b,d,e){if(g.w3&&a&&b){var f={};f.id=a;f.swfVersion=b;f.expressInstall=d;f.callbackFn=e;C[C.length]=f;F(a,!1)}else e&&e({success:!1,id:a})},getObjectById:function(a){if(g.w3)return s(a)},embedSWF:function(a,d,e,f,h,j,l,k,n,p){var r={success:!1,id:d};g.w3&&!(g.wk&&g.wk<312)&&a&&d&&e&&f&&h?(F(d,!1),y(function(){e+="";f+="";var g={};if(n&&typeof n===z)for(var o in n)g[o]=n[o];g.data=a;g.width=e;g.height=f;o={};if(k&&typeof k===z)for(var s in k)o[s]=k[s];if(l&&typeof l===z)for(var u in l)typeof o.flashvars!=
m?o.flashvars+="&"+u+"="+l[u]:o.flashvars=u+"="+l[u];if(v(h))s=b(g,o,d),g.id==d&&F(d,!0),r.success=!0,r.ref=s;else if(j&&t()){g.data=j;w(g,o,d,p);return}else F(d,!0);p&&p(r)})):p&&p(r)},switchOffAutoHideShow:function(){U=!1},ua:g,getFlashPlayerVersion:function(){return{major:g.pv[0],minor:g.pv[1],release:g.pv[2]}},hasFlashPlayerVersion:v,createSWF:function(a,d,e){return g.w3?b(a,d,e):X},showExpressInstall:function(a,b,d,e){g.w3&&t()&&w(a,b,d,e)},removeSWF:function(c){g.w3&&a(c)},createCSS:function(a,
b,d,e){g.w3&&R(a,b,d,e)},addDomLoadEvent:y,addLoadEvent:J,getQueryParamValue:function(a){var b=h.location.search||h.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(a==null)return V(b);for(var b=b.split("&"),d=0;d<b.length;d++)if(b[d].substring(0,b[d].indexOf("="))==a)return V(b[d].substring(b[d].indexOf("=")+1))}return""},expressInstallCallback:function(){if(M){var a=d(T);if(a&&I){a.parentNode.replaceChild(I,a);if(N&&(F(N,!0),g.ie&&g.win))I.style.display="block";P&&P(S)}M=!1}}}}();return e})})})(function(){var e=
window.AmazonUIPageJS||window.P,j=e._namespace||e.attributeErrors;return j?j("SWFObject_AUIBuild"):e}(),window);