(function(q,z,Z){q.guardFatal(function(){q.when("A","jQuery","atf").execute(function(f,a,c){if(a("#bookDescription_feature_div").length){var b=a("#outer_postBodyPS").height();a("#postBodyPS").height()>b+30?(a("#outer_postBodyPS").show(),a("#outer_postBodyPS").css("height",b),a("#psPlaceHolder").show(),a("#expandPS").show(),a("#collapsePS").hide()):(a("#outer_postBodyPS").css("height","auto"),a("#psPlaceHolder").hide());a("#bookDescription_feature_div .a-link-expander").click(function(){a("#bdSeeAllPrompt").is(":hidden")?
(a("#outer_postBodyPS").animate({height:b},500),a("#bdSeeAllPrompt").show(),a("#bdSeeLessPrompt").hide()):(a("#outer_postBodyPS").animate({height:a("#postBodyPS").height()},500),a("#bdSeeAllPrompt").hide(),a("#bdSeeLessPrompt").show());a("#bdExpanderIcon").toggleClass("rotate");return!1})}});q.when("A","jQuery","DynamicIframe","bookDescriptionIframe").execute(function(f,a,c,b){if(a("#bookDescription_feature_div").length){var F=function(){var c=a("#"+I).contentDocument;if(b.staticHeight&&c&&c.defaultView)var f=
parseInt(b.numLines,10),e=c.find("#iframeContent"),c=c.defaultView.getComputedStyle(e,null).getPropertyValue("line-height"),c=parseFloat(c),c=Math.round(c*f);else f=document.getElementById(b.featureDiv).offsetTop,c=document.getElementById(b.imageBlockDiv).offsetTop,e=document.getElementById(b.imageBlockDiv).offsetHeight,c=c+e-f-30,112>c&&(c=112);f=document.getElementById(b.postBodyId).offsetHeight;f>c+30?a("#"+b.seeLessPromptId).hasClass("a-hidden")?(a("#"+b.outerBodyId).height(c),a("#"+b.placeHolderId).removeClass("a-hidden"),
a("#"+b.seeAllPromptId).removeClass("a-hidden")):a("#"+b.outerBodyId).height(f):(a("#"+b.outerBodyId).height(f),a("#"+b.placeHolderId).addClass("a-hidden"),a("#"+b.seeAllPromptId).removeClass("a-hidden"),a("#"+b.seeLessPromptId).addClass("a-hidden"),a("#"+b.expanderIconId).removeClass("rotate"));c=a("#"+b.outerBodyId).height();0==q&&(q=c);c=q;f>c+30&&a("#"+b.seeLessPromptId).is(":hidden")?(a("#"+b.outerBodyId).show(),a("#"+b.outerBodyId).css("height",c),a("#"+b.placeHolderId).show(),a("#expandPS").removeClass("a-hidden"),
a("#collapsePS").addClass("a-hidden")):a("#"+b.outerBodyId).css("height","auto")};var e=null;f=b.encodedDescription;var q=0,y={},I=b.iFrameId;y.iframeId=I;y.iframeWrapperId="bookDesc_iframe_wrapper";y.overriddenCSSId="bookDesc_override_CSS";y.encodedIframeContent=f;y.initialResizeCallback=F;e=new c(y);e.createIframe();"undefined"!==typeof e&&e instanceof c&&(a(z).resize(function(){e.resizeIframe(F)}),a(z).bind("imageResize",function(){e.resizeIframe(F)}));a("#"+b.featureDiv+" .a-link-expander").click(function(){var c=
"#"+b.outerBodyId,f="#"+b.seeAllPromptId,e="#"+b.seeLessPromptId,F="#"+b.expanderIconId,v="#"+b.postBodyId;a(f).hasClass("a-hidden")?(v=q,a(c).animate({height:v},500),a(f).removeClass("a-hidden"),a(e).addClass("a-hidden"),a(F).removeClass("rotate")):(a(c).animate({height:a(v).height()},500),a(f).addClass("a-hidden"),a(e).removeClass("a-hidden"),a(F).addClass("rotate"));return!1})}});q.when("A","jQuery","ImageBlockATF","SampleAudioPlayer","cf").execute(function(f,a,c,b){function F(){var a=z.innerWidth||
document.body.offsetWidth;if(!(0>=a))if(a>c.windowWidthThreshold&&x.width()<=c.configWidths[0]){var a=c.configWidths[1],d=a/c.holderRatio,b=c.frontImageWidth,f=c.frontImageHeight;e(a,d,b,f)}else a<c.windowWidthThreshold&&x.width()>c.configWidths[0]&&(a=c.configWidths[0],d=a/c.holderRatio,c.frontImageAspectRatio>c.holderRatio?(b=a,f=b/c.frontImageAspectRatio):(f=d,b=f*c.frontImageAspectRatio),e(a,d,b,f))}function e(d,b,f,G){if(0<d&&0<b&&0<f&&0<G){X.css("margin-left",d+c.centerColMargin).removeClass("centerColumn");
B.css("width",d);var l=b+c.containerMargin+c.flipLinkMinHeight;x.css("width",d).css("height",l);W(f,G);C.css("height",b-(b-k.outerHeight())/2);d=(C.outerWidth()-k.outerWidth())/2;b=C.outerHeight()-k.outerHeight();m.css("top",b).css("left",d);w.css("top",b+T).css("left",d+f-w.width());a(this).trigger("imageResize");D&&D.hide()}}function W(a,c){k.css("width",a).css("height",c);var d=k.width(),b=k.height();m.css("width",d).css("height",b);"undefined"!==typeof n&&0<n.length&&(n.css("width",d).css("height",
b),l.css("height",b),M&&S&&(b=l.width(),r=(d-b)/2-2,l.removeClass("ieTransition").css("left",(d-b)/2),"front"==g?l.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+r+"px)"):l.css("transform","perspective(3000px) rotateY(90deg) translateZ("+r+"px)"),f.delay(function(){l.addClass("ieTransition")},10)))}function y(){var a=u.find(".audioSamplePopover");q.when("jQuery","a-popover","ready").execute(function(c,d){D=d.create(Y,{activate:"onclick",position:"triggerRight",inlineContent:a})});
G.click(I)}function I(){D&&D.show()}function K(a){a.bind("audioEnded",function(){N.hide();O.hide();G.show();d=0;D&&D.hide()});a.bind("audioPlaying",function(){N.hide();G.hide();O.show();d=1;I()});a.bind("audioPaused",function(){O.hide();G.hide();N.show();d=0;D&&D.hide()})}function Q(){d?H.pause():H.play()}function L(a){if("undefined"!=typeof SitbReader)if("back"==g&&SitbReader.currentBook&&SitbReader.currentBook.bookmarks){a=SitbReader.currentBook.bookmarks.getFirstAndLastPageNumberByName("Back Cover").first;
var d=SitbReader.currentBook.bookmarks.getFirstAndLastPageNumberByName("Back Flap").first;a?SitbReader.LightboxActions.openReaderToPage(a):d?SitbReader.LightboxActions.openReaderToPage(d):SitbReader.LightboxActions.openReader(c.litbData.litbReftag)}else SitbReader.LightboxActions.openReader(c.litbData.litbReftag)}function R(a){S?"click"==a.type?"front"==g?(g="back",k.removeClass("frontUnrotated frontUnrotatedHover").addClass("frontRotated"),n.removeClass("backUnrotated backUnrotatedHover").addClass("backRotated"),
l.css("transform","perspective(3000px) rotateY(90deg) translateZ("+r+"px)"),h.addClass("a-hidden"),t.removeClass("a-hidden"),P.addClass("flipToBackImgRotate")):(g="front",k.removeClass("frontRotated frontRotatedHover").addClass("frontUnrotated"),n.removeClass("backRotated backRotatedHover").addClass("backUnrotated"),l.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+r+"px)"),t.addClass("a-hidden"),h.removeClass("a-hidden"),P.removeClass("flipToBackImgRotate")):"mouseenter"==a.type?
"front"==g?(k.removeClass("frontUnrotated").addClass("frontUnrotatedHover"),n.removeClass("backUnrotated").addClass("backUnrotatedHover"),l.css("transform","perspective(3000px) rotateY(-55deg) translateZ("+r+"px)")):(k.removeClass("frontRotated").addClass("frontRotatedHover"),n.removeClass("backRotated").addClass("backRotatedHover"),l.css("transform","perspective(3000px) rotateY(80deg) translateZ("+r+"px)")):"front"==g?(k.removeClass("frontUnrotatedHover").addClass("frontUnrotated"),n.removeClass("backUnrotatedHover").addClass("backUnrotated"),
l.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+r+"px)")):(k.removeClass("frontRotatedHover").addClass("frontRotated"),n.removeClass("backRotatedHover").addClass("backRotated"),l.css("transform","perspective(3000px) rotateY(90deg) translateZ("+r+"px)")):"click"==a.type?"front"==g?(m.removeClass("bookCanvasTransformHover").addClass("rotated"),h.addClass("a-hidden"),t.removeClass("a-hidden"),P.addClass("flipToBackImgRotate"),g="back"):(m.removeClass("rotated rotatedHover"),t.addClass("a-hidden"),
h.removeClass("a-hidden"),P.removeClass("flipToBackImgRotate"),g="front"):"mouseenter"==a.type?"front"==g?m.addClass("bookCanvasTransformHover"):m.removeClass("rotated").addClass("rotatedHover"):"front"==g?m.removeClass("bookCanvasTransformHover"):m.removeClass("rotatedHover").addClass("rotated")}function v(){E.addClass("parentImage");l.addClass("bookSpine").removeClass("a-hidden");m.addClass("bookCanvasTransition");k.addClass("bookFrontTransition");f.delay(function(){m.addClass("bookCanvasTransformHover");
f.delay(function(){m.removeClass("bookCanvasTransformHover")},1500)},50)}function J(){var a=l.outerWidth(),d=k.outerWidth();r=(d-a)/2-2;l.css("left",(d-a)/2).css("transform","perspective(3000px) rotateY(-90deg) translateZ("+r+"px)");k.addClass("ieTransition ieBookShadow").css("transform-origin","50% 50% -"+a/2+"px");n.addClass("ieTransition backLanding ieBookShadow").removeClass("a-hidden").css("transform-origin","50% 50% -"+a/2+"px");l.addClass("ieTransition ieBookShadow").removeClass("a-hidden").css("transform-origin",
"50% 50% -"+a/2+"px");f.delay(function(){n.removeClass("backLanding").addClass("backUnrotated");k.addClass("frontUnrotated");l.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+r+"px)")},50);k.mouseenter(function(){l.css("transform","perspective(3000px) rotateY(-75deg) translateZ("+r+"px)")});k.mouseleave(function(){l.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+r+"px)")});p.removeClass("a-hidden")}var x=a("#imageBlock"),E=x.find("#img-wrapper"),C=x.find("#imageBlockContainer"),
m=x.find("#img-canvas"),n=m.find(".backImage"),l=m.find(".sideImage"),k=m.find(".frontImage"),w=a("#imageBlockOuter").find("#sitbLogo"),p=x.find(".flipImageToBack"),u=x.find(".sampleBookAudio"),A=0,g="front",M=0,d=0,G=u.find(".audioListenText"),O=u.find(".audioPlayingText"),N=u.find(".audioPausedText"),U=u.find(".audioText"),Y=u.find(".audioPopoverTrigger"),H,h=p.find(".flipToBackText"),t=p.find(".flipToFrontText"),P=p.find(".flipToBackImg"),S=a.browser.msie||!!navigator.userAgent.match(/Trident/),
D,B=a("#leftCol"),X=a("#centerCol"),r=0,V=a("#imageBlockOuter").find("#sitbLogoImg"),T=parseInt(x.css("margin-top"));(function(){var d=E.offset(),g=k.offset();if(g){var e=g.top-d.top,d=g.left-d.left,g=k.outerWidth(),B=k.outerHeight(),h=E.outerHeight()-(E.outerHeight()-k.outerHeight())/2,r=l.outerWidth();E.css("position","relative");w.css("top",e+T).css("left",d+g-w.width());m.css("position","absolute").css("top",e).css("left",d).css("width",g).css("height",B);k.css("position","absolute").css("top",
"0").css("left","0");n.css("position","absolute").css("top","0").css("left","0");l.css("position","absolute").css("top","0").css("left","-"+r+"px");C.css("height",h)}c.audibleData&&c.audibleData.audioSampleSrc&&(H=new b,e={},e.audioSrc=c.audibleData.audioSampleSrc,e.audioId="img-blk-audio-sample",e.audioControllerId=u,e.flashPlayerUrl=c.audibleData.flashPlayerUrl,e.bindEventsCallback=K,H.init(e));g=1;e=["Perspective","TransformStyle","TransformOrigin","BackfaceVisibility","Transition"];for(d=0;d<
e.length;d++)if(g){for(var g=e[d],B=["Webkit","Moz","O","ms"],h=document.createElement("div"),r=!1,t=0;t<B.length;t++)B[t]+g in h.style&&(r=r||!0);"Perspective"===g&&"WebkitPerspective"in h.style&&(r=!1,h.id="test3d",document.body.appendChild(h),3===h.offsetHeight&&(r=!0),h.parentNode.removeChild(h));g=r}(M=(A=g)&&"undefined"!==typeof n&&0<n.length)?(e=k.width(),d=k.height(),0<e&&0<d&&(m.addClass("image-3d"),n.css("width",e).css("height",d),l.css("height",d),S?J():(v(),n.addClass("bookBack").removeClass("a-hidden"),
p.removeClass("a-hidden")),H&&H.isPlayerAvailable?p.addClass("a-span6"):p.addClass("a-span12"),f.declarative("flip-action",["click","mouseenter","mouseleave"],R))):m.addClass("image-2d");c&&c.litbData&&c.litbData.hasLitb&&c.litbData.litbReftag&&(V.removeClass("a-hidden"),V.click(L),m.click(L));H&&H.isPlayerAvailable&&(M?u.addClass("a-span6"):u.addClass("a-span12"),O.hide(),N.hide(),u.removeClass("a-hidden"),U.children().click(Q),e=parseInt,d=G.outerWidth(),g=O.outerWidth(),B=N.outerWidth(),h=0,0<
d&&0<g&&0<B&&(h=Math.max(d,g,B)+5),(e=e(h))&&0<e&&U.css("width",e),y());c.disableResize||a(z).resize(F)})()});q.when("A","jQuery","ImageBlockATF","ImageGalleryMarkup").execute(function(f,a,c){function b(){var a=c.imageGalleryData;if(a&&0<a.length){p={};u=a.length;for(var b=0;b<a.length;b++)p["ig-thumb-"+b]=a[b]}}function q(){w=J.height();0<x.length&&(w-=x.height());if(a.browser.msie&&7==a.browser.version){var d=E.outerHeight()-E.height();d&&0<d&&(w-=d)}if(w&&0<w){E.css("height",w);var d=l.height(),
b=l.width();C.css("height",d).css("width",b).data("height",d).data("width",b)}}function e(){if(0<J.length){q();y();if(0<u)for(var d=0;d<u;d++){var b="ig-thumb-"+d,b=a('<div class="ig-thumb-image"><img class="ig-thumb-inner '+(b==g?"selected":"")+'" id="'+b+'" src="'+p[b].thumbUrl+'"></div>');n.append(b)}zoomOptions=K();A.setImageData(zoomOptions);A.attachZoomEvents()}}function z(){var a=p[g].dimensions[0],b=p[g].dimensions[1];m.css("max-width",a).css("max-height",b).removeClass("image-stretch-horizontal image-stretch-vertical");
m.addClass(I(a,b))}function y(){p[g]&&(z(),m.attr("src",p[g].mainUrl))}function I(a,b){var c=C.data("width")/C.data("height"),f="image-stretch-vertical";a/b>c&&(f="image-stretch-horizontal");return f}function K(){var a={};p[g]&&(a.containerId="igInner",a.imageId="igImage",a.imageWidth=p[g].dimensions[0],a.imageHeight=p[g].dimensions[1]);return a}function Q(){p&&n.find(".ig-thumb-inner").click(function(){var b=this.id,c=a(this),f=p[b];!c.hasClass("selected")&&f&&(g=b,n.find(".selected").removeClass("selected"),
c.addClass("selected"),A.detachEvents(),m.addClass("a-hidden"),k.show(),document.getElementById("igImage").onload=M,y(),b=K(),A.setImageData(b))})}function L(){var a=f.viewport();v.closest(".a-popover-modal").css("width",.75*a.width).css("height",.75*a.height);q();A.detachEvents();z();a=K();A.setImageData(a);A.attachZoomEvents()}function R(){f.capabilities.orientation&&(f.on("orientationchange",function(){L()}),f.on("a:popover:afterHide:imageGallery",function(){f.off("a:popover:afterHide:imageGallery");
f.on("a:popover:beforeShow:imageGallery",function(){L()})}))}var v=a("#imgGalleryContent"),J=v.closest(".a-popover-wrapper"),x=J.find(".a-popover-header"),E=J.find(".a-popover-inner"),C=v.find("#igInner"),m=C.find("#igImage"),n=v.find(".ig-thumbs"),l=v.find(".ig-main-image"),k=v.find(".loading-bar"),w=0,p=null,u=0,A=new function(){function b(){t.bind("touchstart.ig touchmove.ig",function(a){c(a);t.unbind("touchstart.ig touchmove.ig");t.bind("touchmove.ig",function(a){c(a)});t.bind("touchend.ig",function(a){e.zoomOut();
t.unbind("touchstart.ig touchmove.ig touchend.ig");b()})})}function c(a){q&&a.preventDefault();var b,d={},f=h.width(),g=h.height();b=a.pageX-h.offset().left;a=a.pageY-h.offset().top;d.x=n?b*l/f-b:0;d.y=p?a*m/g-a:0;e.zoomIn(d)}var e={},g=null,k=null,l=0,m=0,h=null,t=null,n=!1,p=!1,q=f.capabilities.touch;e.setImageData=function(b){g=b.containerId;k=b.imageId;l=b.imageWidth;m=b.imageHeight;h=a("#"+g);t=a("#"+k);n=0<l&&0<h.length&&l>h.width();p=0<m&&0<h.length&&m>h.height()};e.attachZoomEvents=function(){if(n||
p)h.addClass("zoomable"),q?b():t.click(function(a){h.hasClass("zoomed-in")?(e.zoomOut(),t.unbind("mousemove")):h.hasClass("zoomed-out")&&(c(a),t.mousemove(function(a){c(a)}))})};e.zoomIn=function(a){t.css("top",-1*a.y);t.css("left",-1*a.x);h.removeClass("zoomed-out").addClass("zoomed-in")};e.zoomOut=function(){h.removeClass("zoomed-in").addClass("zoomed-out");t.css("top","auto").css("left","auto")};e.detachEvents=function(){e.zoomOut();t.unbind();h.removeClass("zoomable")};return e},g;0<v.length&&
(g="ig-thumb-0",k.hide(),b(),e(),Q(),R());var M=function(){k.hide();m.removeClass("a-hidden");A.attachZoomEvents()}});q.when("A","jQuery").execute(function(f,a){if(a("#imageBlockThumbs").length){var c=function(){var b=a("#imgThumbs"),c=b.data("a-modal"),e=f.viewport();c.width=.75*e.width;c.height=.75*e.height;b.data("a-modal",c)};c();f.on("resize",c)}})})()})(function(){var q=window.AmazonUIPageJS||window.P,z=q._namespace||q.attributeErrors;return z?z("MSXBooksDetailPageAsset"):q}(),
window);
/* ******** */
(function(v,w,P){v.execute(function(){v.when("A","jQuery","atf").execute(function(u,d,f){var k=d("#rbbContainer");k.find(".rbbHeaderLink").attr("href","javascript:void(0);");k.find(".rbbHeader .displayNone i.prime").hide();k.find(".rbbHeader .displayNone .primeBadge").hide();k.find(".rbbHeader .ubbPrimeBadge").hide();k.find(".rbbHeader .prime-plus-price").hide();k.find(".rbbHeader .displayNone").removeClass("displayNone");d("#rbbContainer .rbbSection.unselected .dp-accordion-inner").hide();var c=
d("#buyDealSection").length;d("#rbbContainer .rbbSection .rbbHeader").click(function(a){d(a.target);a=d(this);a=a.hasClass("rbbHeader")?a:a.parents(".rbbHeader");if(a.parents(".rbbSection").hasClass("selected"))return!1;k.find(".selected .a-icon-radio-active").removeClass("a-icon-radio-active").addClass("a-icon-radio-inactive");k.find(".selected .offer-price").removeClass("a-color-price a-size-medium").addClass("a-color-base a-size-base");k.find("i.a-icon.prime").hide();k.find(".primeBadge").hide();
k.find(".ubbPrimeBadge").hide();var b=k.find(".prime-plus-price-grid");b.hasClass("hidden")?b.removeClass("hidden").show():b.addClass("hidden").hide();k.find(".prime-plus-price").show();a.parents(".rbbSection").removeClass("unselected").addClass("selected");a.parents(".rbbSection").toggleClass("dp-accordion-active",500);a.find(".a-icon-radio-inactive").removeClass("a-icon-radio-inactive").addClass("a-icon-radio-active");a.find(".offer-price").removeClass("a-color-base a-size-base").addClass("a-color-price a-size-medium");
a.find("i.a-icon.prime").show();a.find(".primeBadge").show();a.find(".prime-plus-price").hide();d("#rbbContainer .rbbSection .rbbContent").find(".offer-price").removeClass("a-color-base").addClass("a-color-price");a.find(".ubbPrimeBadge").show();var e=d(this).attr("id"),f,g;k.find(".rbbSection").each(function(a,b){d(b).find(".rbbHeader")[0].id==e?f=d(b):d(b).hasClass("selected")&&(g=d(b))});g.find(".rbbContent").slideUp(500,function(){g.removeClass("selected").addClass("unselected");g.toggleClass("dp-accordion-active",
500)});f.find(".rbbContent").slideDown(500);d.browser.msie&&7==parseInt(d.browser.version,10)&&(f.find(".rbbContent").css("display","inline"),setTimeout(function(){f.find(".rbbContent").css("display","block")},505));if(c&&"undefined"!=typeof UDPDealView)if(d("#gbld_header_message").show(),"buyDealSection"==e)UDPDealView.prototype.onSelectLDBuybox();else UDPDealView.prototype.onSelectRegularBuybox();return!0})});v.when("A","jQuery").execute(function(u,d){d("#one-click-button-ubb, #usedbuyBox #add-to-cart-button-ubb").click(function(){var f=
d("#addToCart"),k=f.attr("action").replace("ref=dp_start-bbf_1_glance","ref=dp_start-ubbf_1_glance");f.attr("action",k);return!0});v.when("a-popover").execute(function(f){var k=d("#usedItemConditionInfoLink"),c=f.create(k,{width:250,position:"triggerBottom",activate:u.capabilities.touch?"onmousemove":"onclick",closeButton:!1,popoverLabel:"Used condition details",name:"usedItemConditionDetailsPopover",dataStrategy:"preload"});k.mouseleave(function(){c.hide()})})})})})(function(){var v=window.AmazonUIPageJS||
window.P,w=v._namespace||v.attributeErrors;return w?w("OffersBooksDetailPageAsset"):v}(),window);
/* ******** */
(function(v,w,P){v.execute(function(){v.when("A","jQuery","atf").execute(function(u,d,f){var k,c=0;v.when("DPClientLogger").execute(function(){"undefined"!=typeof w.DPClientLogger&&(k=new w.DPClientLogger.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))});d("#bookDetails_feature_div .hero-more").click(function(a){a.preventDefault();a=d(this).attr("data-popupID");var b=d("#"+a),e=d(this).offset().left+d(this).width()/2,f=d("#popupContent").offset().left,e=(e-f)/d("#popupContent").width()*100;
d("#"+a+" .pointer").css({left:e+"%"});d("#popupContent .details-popup").filter(":visible").length?d("#popupContent .details-popup").filter(":visible").attr("id")!==a?(d("#popupContent .details-popup").filter(":visible").slideToggle(300),b.slideToggle(300)):b.slideUp(300):(b.slideDown(300),d(this).hasClass("hero-more")&&d("html,body").animate({scrollTop:d("#bookDetails_feature_div").offset().top-50},600));k&&!c&&(k.logImpression("ma-books-br-details"),c=1)});d("#bookDetails_feature_div .moreNarratorLink").click(function(){if(location.pathname.replace(/^\//,
"")==this.pathname.replace(/^\//,"")||location.hostname==this.hostname){var a=d(this.hash),a=a.length?a:d("[name="+this.hash.slice(1)+"]");a.length&&d("html,body").animate({scrollTop:a.offset().top},1E3);return!1}});d("#bookDetails_feature_div .details-popup button").click(function(a){d(this).parent().slideUp(300)})});v.when("A","jQuery","atf").execute(function(u,d,f){function k(){var c=parseInt(d("#byline").width()),a=0;d("#byline .author").each(function(){d(this).is(".notFaded")&&(a+=d(this).outerWidth())});
a+=d("#byline .more").outerWidth();if(a>c){var b=d("#byline .author.notFaded").length;d(d("#byline .author.notFaded").get().reverse()).each(function(e){a>c&&e<b-1&&(e=d(this).width(),d(this).removeClass("notFaded"),d(this).fadeOut(10,function(){d(this).hide()}),a-=e,d("#byline .moreCount").html(d("#byline .author").length-d("#byline .author.notFaded").length),d("#byline .more").addClass("notFaded").fadeIn(10))})}else if(a<c&&d("#byline .author.notFaded").length<d("#byline .author").length){var e=
c-a;d("#byline .author").each(function(){if(!d(this).hasClass("notFaded")){var a=d(this).outerWidth();a<=e?(e-=a,d(this).addClass("notFaded").fadeIn(10),a=d("#byline .author").length-d("#byline .author.notFaded").length,0===a?d("#byline .more").removeClass("notFaded").fadeOut(10):(d("#byline .moreCount").html(a),d("#byline .more").addClass("notFaded").fadeIn(10))):e=0}})}}d("#byline .showMoreLink").click(function(){d("#byline .author").each(function(){d(this).hasClass("notFaded")||d(this).addClass("notFaded").fadeIn(0);
d("#byline .more").removeClass("notFaded").fadeOut(0)});return!1});d("#byline .contributorNameID").mouseenter(function(){var c=d(this).attr("data-asin"),a={},b="isAjaxComplete_"+c,e="isAjaxInProgress_"+c,f=u.state("popoverImage-state");a.entityID=c;"1"!==f[b]&&"1"!==f[e]&&(d.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:a,dataType:"html",timeout:1E3,success:function(a){d("#contributorImageContainer"+c).get(0).innerHTML=a;f[b]="1";u.state("popoverImage-state",
f)},error:function(){f[e]="0";u.state("popoverImage-state",f)}}),f[e]="1",u.state("popoverImage-state",f))});(function(c){var a=parseInt(c.width()),b=parseInt(c.find(".more").outerWidth()),e=0;d("#byline .author").each(function(){d(this).is(".notFaded")&&(e+=d(this).outerWidth())});d("#byline .more").attr("data-width",b);var f=a-b;if(f>e)c.find(".author").each(function(){var a=d(this).index();3<=parseInt(a)?(a=d(this).outerWidth(),d(this).attr("data-width",a),a<f?(f-=a,d(this).addClass("notFaded"),
d(this).fadeIn("slow")):(f=0,d(this).fadeOut("slow"))):(a=d(this).outerWidth(),d(this).attr("data-width",a),f-=a)});else{var g=d("#byline .author.notFaded").length;d(d("#byline .author.notFaded").get().reverse()).each(function(a){f<e&&a<g-1&&(a=d(this).outerWidth(),e-=a,d(this).fadeOut("slow").removeClass("notFaded"))})}a=c.find(".author").length-c.find(".author.notFaded").length;0<a&&(c.find(".moreCount").html(a),c.find(".more").fadeIn("slow"),c.find(".more").addClass("notFaded"))})(u.$("#byline"));
d(w).resize(function(){k()})});v.when("A","jQuery","DynamicIframe","ProductDescriptionData","cf").execute(function(u,d,f,k){function c(){q=0;var a=Math.min(m,l.length);b(0,a)}function a(){0<t.length&&0<v.length&&(w="collapsed",t.removeClass("a-hidden"),t.click(function(){"collapsed"===w?(n?v.animate({height:"show"}):(v.removeClass("extraReviews"),b(q,l.length),n=1),t.removeClass("collapsed").addClass("expanded"),w="expanded"):(v.animate({height:"hide"}),t.removeClass("expanded").addClass("collapsed"),
w="collapsed")}))}function b(a,b){var c;for(c=a;c<b;c++){var h={};h.iframeId="er_iframe_"+c;h.iframeWrapperId="er_iframe_wrapper_"+c;h.iframeContainerId="er_container_"+c;h.iframeExpanderId="er_expander_"+c;h.iframeColumnId="er_column_"+c;var k=h,m=l[c],n="<h3 class='erSource'>"+m.source+"</h3><div class='erContent'>"+m.content+"</div>";m.footnote&&(n=n+"<em class='erFootnote'>"+m.footnote+"</em>");k.encodedIframeContent=n;h.initialResizeCallback=e;k=h;m={};m.id=d("#"+k.iframeId);m.column=d("#"+k.iframeColumnId);
m.wrapper=d("#"+k.iframeWrapperId);m.container=d("#"+k.iframeContainerId);m.expander=d("#"+k.iframeExpanderId);m.iframeObj=new f(k);m.state="full";k=m;r[h.iframeId]=k;k.column.removeClass("extraReviews");k&&"undefined"!=typeof k.iframeObj&&"function"==typeof k.iframeObj.createIframe&&k.iframeObj.createIframe();g(k);q++}}function e(a){(a=r[a])&&170<a.wrapper.outerHeight()&&(a.container.css("height",140),a.expander.removeClass("a-hidden expanded").addClass("collapsed"),a.state="partial")}function h(a){(a=
r[a])&&"full"===a.state&&a.container.css("height",a.wrapper.outerHeight())}function g(a){if(a&&"undefined"!=typeof a.iframeObj&&"function"==typeof a.iframeObj.resizeIframe)u.on("resize",function(){a.iframeObj.resizeIframe(h)});a&&a.expander&&a.expander.click(function(){"partial"===a.state?(a.container.animate({height:a.wrapper.outerHeight()}),a.expander.removeClass("collapsed").addClass("expanded"),a.state="full"):(a.container.animate({height:140}),a.expander.removeClass("expanded").addClass("collapsed"),
d("html, body").animate({scrollTop:a.container.offset().top-20}),a.state="partial")})}var l=k.encodedReviews,m=parseInt(k.reviewsPerRow),q=0,n=0;k=d("#productDescription-multiColumn");var r={},t,v,w;0<k.length&&l&&0<l.length&&m&&(t=k.find(".reviewsExpander"),v=k.find(".seeMoreProductReviews"),c(),a())})})})(function(){var v=window.AmazonUIPageJS||window.P,w=v._namespace||v.attributeErrors;return w?w("PInfoBooksDetailPageAsset"):v}(),window);
/* ******** */
(function(v,w,P){v.execute(function(){v.when("A","jQuery","swfobject").register("SampleAudioPlayer",function(u,d,f){function k(a){function b(){k.audioId.trigger("audioEnded")}function c(){k.audioId.trigger("audioPlaying")}function f(){k.audioId.trigger("audioPaused")}function g(){k.audioId.trigger("audioReady")}var k={initializePlayer:function(a){k.options=a;k.isFirstPlay=1},play:function(){if(k.isFirstPlay){var m=k.options,q=d('<audio id="'+m.audioId+'" src="'+m.audioSrc+'"></audio>');m.audioControllerId.append(q);
k.audioObj=d("#"+m.audioId).get(0);k.audioId=d("#"+m.audioId);k.audioObj.addEventListener("ended",b);k.audioObj.addEventListener("playing",c);k.audioObj.addEventListener("pause",f);k.audioObj.addEventListener("loadeddata",g);"function"==typeof a.bindEventsCallback&&a.bindEventsCallback(k.audioId);k.isFirstPlay=0}k.audioObj.play()},pause:function(){k.audioObj.pause()}};return k}function c(a){var b={};w.Mp3Interface||(w.Mp3Interface={currentPlayer:null,setCurrentPlayer:function(a){a&&(Mp3Interface.currentPlayer&&
Mp3Interface.currentPlayer.audioId!==a.audioId&&(f.getObjectById(Mp3Interface.currentPlayer.audioId).stopSong(),Mp3Interface.currentPlayer.isPlaying=0),Mp3Interface.currentPlayer=a)},callback:function(a){Mp3Interface.currentPlayer&&("onPlayerInit"==a?Mp3Interface.currentPlayer.audioId.trigger("audioReady"):"onPlay"==a?(Mp3Interface.currentPlayer.audioId.trigger("audioPlaying"),Mp3Interface.currentPlayer.isPlaying=1):"onPause"==a?(Mp3Interface.currentPlayer.audioId.trigger("audioPaused"),Mp3Interface.currentPlayer.isPlaying=
0):"onComplete"==a&&(Mp3Interface.currentPlayer.audioId.trigger("audioEnded"),Mp3Interface.currentPlayer.isPlaying=0,Mp3Interface.currentPlayer.isFirstPlay=1))}});b.initializePlayer=function(a){b.isFirstPlay=1;b.options=a;Mp3Interface.setCurrentPlayer(this);a.audioControllerId.append('<div id="'+a.audioId+'"></div>');var c=a.flashPlayerUrl,g=a.audioId,k=a.minFlashVersion,m={protocol:w.location.protocol.replace(":","")};f.embedSWF(c,g,1,1,k,null,m,{allowScriptAccess:"always"});b.audioId=d("#"+a.audioId);
"function"==typeof a.bindEventsCallback&&a.bindEventsCallback(b.audioId);b.isPlaying=0};b.play=function(){b.isPlaying||(Mp3Interface.setCurrentPlayer(this),b.isFirstPlay?(f.getObjectById(b.options.audioId).playSong(a.audioSrc),b.isFirstPlay=0):f.getObjectById(b.options.audioId).pauseSong())};b.pause=function(){b.isPlaying&&(Mp3Interface.setCurrentPlayer(this),f.getObjectById(b.options.audioId).pauseSong())};return b}return function(){var a={init:function(b){if("undefined"!==typeof b.audioSrc&&"undefined"!==
typeof b.audioId&&"undefined"!==typeof b.audioControllerId){var d=b.audioSrc,h=document.createElement("audio"),g,l,d=d.match("[^.]+$");0<d.length&&(g=d[0],"mp3"==g?l="audio/mpeg":"ogg"==g?l="audio/ogg":"wav"==g&&(l="audio/wav"));g=l+'; codecs="'+g+'"';l=0;h&&h.canPlayType&&h.canPlayType(g)&&h.canPlayType(g).replace(/no/,"")&&(l=1);l?(a.player=new k(b),a.player.initializePlayer(b),a.isPlayerAvailable=1):b.flashPlayerUrl&&f&&f.hasFlashPlayerVersion("9.0.0")&&(b.minFlashVersion="9.0.0",a.player=new c(b),
a.player.initializePlayer(b),a.isPlayerAvailable=1)}},pause:function(){"undefined"!==typeof a.player&&a.player.pause()},play:function(){"undefined"!==typeof a.player&&a.player.play()}};return a}});v.register("swfobject",function(){var u=function(){function d(){if(!K){try{var a=p.getElementsByTagName("body")[0].appendChild(p.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}K=!0;for(var a=D.length,c=0;c<a;c++)D[c]()}}function f(a){K?a():D[D.length]=a}function k(a){if("undefined"!=
typeof E.addEventListener)E.addEventListener("load",a,!1);else if("undefined"!=typeof p.addEventListener)p.addEventListener("load",a,!1);else if("undefined"!=typeof E.attachEvent)r(E,"onload",a);else if("function"==typeof E.onload){var b=E.onload;E.onload=function(){b();a()}}else E.onload=a}function c(){var b=p.getElementsByTagName("body")[0],c=p.createElement("object");c.setAttribute("type","application/x-shockwave-flash");var d=b.appendChild(c);if(d){var e=0;(function(){if("undefined"!=typeof d.GetVariable){var f=
d.GetVariable("$version");f&&(f=f.split(" ")[1].split(","),I.pv=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)])}else if(10>e){e++;setTimeout(arguments.callee,10);return}b.removeChild(c);d=null;a()})()}else a()}function a(){var a=M.length;if(0<a)for(var c=0;c<a;c++){var d=M[c].id,f=M[c].callbackFn,k={success:!1,id:d};if(0<I.pv[0]){var l=n(d);if(l)if(!t(M[c].swfVersion)||I.wk&&312>I.wk)if(M[c].expressInstall&&e()){k={};k.data=M[c].expressInstall;k.width=l.getAttribute("width")||"0";k.height=
l.getAttribute("height")||"0";l.getAttribute("class")&&(k.styleclass=l.getAttribute("class"));l.getAttribute("align")&&(k.align=l.getAttribute("align"));for(var m={},l=l.getElementsByTagName("param"),q=l.length,p=0;p<q;p++)"movie"!=l[p].getAttribute("name").toLowerCase()&&(m[l[p].getAttribute("name")]=l[p].getAttribute("value"));h(k,m,d,f)}else g(l),f&&f(k);else y(d,!0),f&&(k.success=!0,k.ref=b(d),f(k))}else y(d,!0),f&&((d=b(d))&&"undefined"!=typeof d.SetVariable&&(k.success=!0,k.ref=d),f(k))}}function b(a){var b=
null;(a=n(a))&&"OBJECT"==a.nodeName&&("undefined"!=typeof a.SetVariable?b=a:(a=a.getElementsByTagName("object")[0])&&(b=a));return b}function e(){return!L&&t("6.0.65")&&(I.win||I.mac)&&!(I.wk&&312>I.wk)}function h(a,b,c,d){L=!0;H=d||null;ga={success:!1,id:c};var e=n(c);if(e){"OBJECT"==e.nodeName?(N=l(e),J=null):(N=e,J=c);a.id="SWFObjectExprInst";if("undefined"==typeof a.width||!/%$/.test(a.width)&&310>parseInt(a.width,10))a.width="310";if("undefined"==typeof a.height||!/%$/.test(a.height)&&137>parseInt(a.height,
10))a.height="137";p.title=p.title.slice(0,47)+" - Flash Player Installation";d=I.ie&&I.win?"ActiveX":"PlugIn";d="MMredirectURL="+E.location.toString().replace(/&/g,"%26")+"&MMplayerType="+d+"&MMdoctitle="+p.title;b.flashvars="undefined"!=typeof b.flashvars?b.flashvars+("&"+d):d;I.ie&&I.win&&4!=e.readyState&&(d=p.createElement("div"),c+="SWFObjectNew",d.setAttribute("id",c),e.parentNode.insertBefore(d,e),e.style.display="none",function(){4==e.readyState?e.parentNode.removeChild(e):setTimeout(arguments.callee,
10)}());m(a,b,c)}}function g(a){if(I.ie&&I.win&&4!=a.readyState){var b=p.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(l(a),b);a.style.display="none";(function(){4==a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(l(a),a)}function l(a){var b=p.createElement("div");if(I.win&&I.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName("object")[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)1==a[d].nodeType&&
"PARAM"==a[d].nodeName||8==a[d].nodeType||b.appendChild(a[d].cloneNode(!0));return b}function m(a,b,c){var d,e=n(c);if(I.wk&&312>I.wk)return d;if(e)if("undefined"==typeof a.id&&(a.id=c),I.ie&&I.win){var f="",g;for(g in a)a[g]!=Object.prototype[g]&&("data"==g.toLowerCase()?b.movie=a[g]:"styleclass"==g.toLowerCase()?f+=' class="'+a[g]+'"':"classid"!=g.toLowerCase()&&(f+=" "+g+'="'+a[g]+'"'));g="";for(var h in b)b[h]!=Object.prototype[h]&&(g+='<param name="'+h+'" value="'+b[h]+'" />');e.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+
f+">"+g+"</object>";G[G.length]=a.id;d=n(a.id)}else{h=p.createElement("object");h.setAttribute("type","application/x-shockwave-flash");for(var k in a)a[k]!=Object.prototype[k]&&("styleclass"==k.toLowerCase()?h.setAttribute("class",a[k]):"classid"!=k.toLowerCase()&&h.setAttribute(k,a[k]));for(f in b)b[f]!=Object.prototype[f]&&"movie"!=f.toLowerCase()&&(a=h,g=f,k=b[f],c=p.createElement("param"),c.setAttribute("name",g),c.setAttribute("value",k),a.appendChild(c));e.parentNode.replaceChild(h,e);d=h}return d}
function q(a){var b=n(a);b&&"OBJECT"==b.nodeName&&(I.ie&&I.win?(b.style.display="none",function(){if(4==b.readyState){var c=n(a);if(c){for(var d in c)"function"==typeof c[d]&&(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):b.parentNode.removeChild(b))}function n(a){var b=null;try{b=p.getElementById(a)}catch(c){}return b}function r(a,b,c){a.attachEvent(b,c);ia[ia.length]=[a,b,c]}function t(a){var b=I.pv;a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||
0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function v(a,b,c,d){if(!I.ie||!I.mac){var e=p.getElementsByTagName("head")[0];e&&(c=c&&"string"==typeof c?c:"screen",d&&(Z=O=null),O&&Z==c||(d=p.createElement("style"),d.setAttribute("type","text/css"),d.setAttribute("media",c),O=e.appendChild(d),I.ie&&I.win&&"undefined"!=typeof p.styleSheets&&0<p.styleSheets.length&&(O=p.styleSheets[p.styleSheets.length-1]),Z=c),I.ie&&I.win?O&&"object"==
typeof O.addRule&&O.addRule(a,b):O&&"undefined"!=typeof p.createTextNode&&O.appendChild(p.createTextNode(a+" {"+b+"}")))}}function y(a,b){if(Q){var c=b?"visible":"hidden";K&&n(a)?n(a).style.visibility=c:v("#"+a,"visibility:"+c)}}function C(a){return null!=/[\\\"<>\.;]/.exec(a)&&"undefined"!=typeof encodeURIComponent?encodeURIComponent(a):a}var E=w,p=document,z=navigator,F=!1,D=[function(){F?c():a()}],M=[],G=[],ia=[],N,J,H,ga,K=!1,L=!1,O,Z,Q=!0,I=function(){var a="undefined"!=typeof p.getElementById&&
"undefined"!=typeof p.getElementsByTagName&&"undefined"!=typeof p.createElement,b=z.userAgent.toLowerCase(),c=z.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,e=!+"\v1",f=[0,0,0],g=null;if("undefined"!=typeof z.plugins&&"object"==typeof z.plugins["Shockwave Flash"])!(g=z.plugins["Shockwave Flash"].description)||"undefined"!=typeof z.mimeTypes&&z.mimeTypes["application/x-shockwave-flash"]&&
!z.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(F=!0,e=!1,g=g.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),f[0]=parseInt(g.replace(/^(.*)\..*$/,"$1"),10),f[1]=parseInt(g.replace(/^.*\.(.*)\s.*$/,"$1"),10),f[2]=/[a-zA-Z]/.test(g)?parseInt(g.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0);else if("undefined"!=typeof E.ActiveXObject)try{var h=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");h&&(g=h.GetVariable("$version"))&&(e=!0,g=g.split(" ")[1].split(","),f=[parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],
10)])}catch(k){}return{w3:a,pv:f,wk:b,ie:e,win:d,mac:c}}();(function(){I.w3&&(("undefined"!=typeof p.readyState&&"complete"==p.readyState||"undefined"==typeof p.readyState&&(p.getElementsByTagName("body")[0]||p.body))&&d(),K||("undefined"!=typeof p.addEventListener&&p.addEventListener("DOMContentLoaded",d,!1),I.ie&&I.win&&(p.attachEvent("onreadystatechange",function(){"complete"==p.readyState&&(p.detachEvent("onreadystatechange",arguments.callee),d())}),E==top&&function(){if(!K){try{p.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,
0);return}d()}}()),I.wk&&function(){K||(/loaded|complete/.test(p.readyState)?d():setTimeout(arguments.callee,0))}(),k(d)))})();(function(){I.ie&&I.win&&w.attachEvent("onunload",function(){for(var a=ia.length,b=0;b<a;b++)ia[b][0].detachEvent(ia[b][1],ia[b][2]);a=G.length;for(b=0;b<a;b++)q(G[b]);for(var c in I)I[c]=null;I=null;for(var d in u)u[d]=null;u=null})})();return{registerObject:function(a,b,c,d){if(I.w3&&a&&b){var e={};e.id=a;e.swfVersion=b;e.expressInstall=c;e.callbackFn=d;M[M.length]=e;y(a,
!1)}else d&&d({success:!1,id:a})},getObjectById:function(a){if(I.w3)return b(a)},embedSWF:function(a,b,c,d,g,k,l,n,q,p){var r={success:!1,id:b};I.w3&&!(I.wk&&312>I.wk)&&a&&b&&c&&d&&g?(y(b,!1),f(function(){c+="";d+="";var f={};if(q&&"object"===typeof q)for(var u in q)f[u]=q[u];f.data=a;f.width=c;f.height=d;u={};if(n&&"object"===typeof n)for(var v in n)u[v]=n[v];if(l&&"object"===typeof l)for(var w in l)u.flashvars="undefined"!=typeof u.flashvars?u.flashvars+("&"+w+"="+l[w]):w+"="+l[w];if(t(g))v=m(f,
u,b),f.id==b&&y(b,!0),r.success=!0,r.ref=v;else{if(k&&e()){f.data=k;h(f,u,b,p);return}y(b,!0)}p&&p(r)})):p&&p(r)},switchOffAutoHideShow:function(){Q=!1},ua:I,getFlashPlayerVersion:function(){return{major:I.pv[0],minor:I.pv[1],release:I.pv[2]}},hasFlashPlayerVersion:t,createSWF:function(a,b,c){return I.w3?m(a,b,c):P},showExpressInstall:function(a,b,c,d){I.w3&&e()&&h(a,b,c,d)},removeSWF:function(a){I.w3&&q(a)},createCSS:function(a,b,c,d){I.w3&&v(a,b,c,d)},addDomLoadEvent:f,addLoadEvent:k,getQueryParamValue:function(a){var b=
p.location.search||p.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(null==a)return C(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return C(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(L){var a=n("SWFObjectExprInst");a&&N&&(a.parentNode.replaceChild(N,a),J&&(y(J,!0),I.ie&&I.win&&(N.style.display="block")),H&&H(ga));L=!1}}}}();return u})})})(function(){var v=window.AmazonUIPageJS||window.P,w=v._namespace||v.attributeErrors;
return w?w("PlatformBooksDetailPageAsset"):v}(),window);
/* ******** */
(function(v,w,P){v.execute(function(){v.when("A","jQuery","atf").execute(function(u,d){u.on.ready(function(){function f(a,b,c,e,f){d(a).slideToggle(300);d(b).slideToggle(300);d(c).toggleClass("tmmShowPrompt tmmHidePrompt");d(e).toggleClass("tmmShowPrompt tmmHidePrompt");d(f).toggleClass("rotate")}function k(a){a.position();a.width();d(".swatchElement");a.find(".swatchElement").each(function(){d(this).attr("data-width",d(this).width())});d("#formats").find(".a-row").removeClass("nonJSFormats")}function c(){var a=
d("#formats"),b=a.width()-40,c=0;a.find(".swatchElement").each(function(){d(this).is(":visible")&&(c+=d(this).width())});c>b?d(a.find(".swatchElement:visible").get().reverse()).each(function(){var a=0,e=!1;d(this).find(".format").hasClass("a-button-selected")?(a=d(this).prev(".swatchElement").width(),e=d(this).prev(".swatchElement").is(":hidden"),d(this).prev(".swatchElement").hide()):(a=d(this).width(),e=d(this).is(":hidden"),d(this).hide());e||(c-=a);return c>b}):c<b&&a.find(".swatchElement").each(function(){if(d(this).is(":hidden"))return d(this).attr("data-width")<=
b-c&&d(this).show(),!1})}var a=0,b=0,e,h=function(a){"undefined"!=typeof a&&(e=new a.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))};"undefined"!=typeof amznJQ?amznJQ.available("DPClientLogger",function(){h(w.DPClientLogger)}):v.when("DPClientLogger").execute(h);u.declarative("tmm-see-more-editions-click",["click"],function(a){var b=a.data,c=b.metabindingUrl;if(a.$target.hasClass("a-link-expander")||a.$target.parent().hasClass("a-link-expander")){var b=b.metabindingPlaceHolder,e="#metabinding_row_top_"+
b,g="#metabinding_row_bottom_"+b,h="#editionsSeePrompt_"+b,k="#editionsHidePrompt_"+b,l="#editionsIcon_"+b,v="isAjaxComplete_"+b,p="isAjaxInProgress_"+b;a="#tmmSpinnerDiv_"+b;var z=u.state("mediamatrix-state"),b=z["url_"+b].replace(/&amp;/g,"&");d("#formats .tmmErrorClass").hide();"1"===z[v]||"1"===z[p]?f(e,g,h,k,l):(u.ajax(b,{method:"get",success:function(){z[v]="1";u.state("mediamatrix-state",z);f(e,g,h,k,l)},indicator:d(a),error:function(){d($tmmErrorDiv).show();z[p]="0";u.state("mediamatrix-state",
z)}}),z[p]="1",u.state("mediamatrix-state",z))}else"#"!==c&&(w.location=c)});if(0<d("#formats > .a-link-expander").length){var g=w.ue;g&&g.count&&g.count("mediaMatrixExpanderPresent",1)}d("#formats > .a-link-expander").click(function(){f("#tmmSwatches","#twister","#showMoreFormatsPrompt","#hideMoreFormatsPrompt","#formatsIcon");if(!b){var c=w.ue;c&&c.count&&c.count("mediaMatrixExpanderClicked",1);b=1}e&&d("#twister").is(":visible")&&!a&&(e.logImpression("tmm-show-more-formats-viewed"),a=1)});d("#formats.responsive").each(function(){k(d(this))});
var g=u.state("mediamatrixState"),l="false";"undefined"!==typeof g&&"undefined"!==typeof g.swatchWrap&&(l=g.swatchWrap);"true"!=l&&(c(),u.on("resize",c));d("#formats .unselected .format").mouseenter(function(){d(this).find(".a-color-secondary").addClass("a-color-price").removeClass("a-color-secondary")}).mouseleave(function(){d(this).find(".a-color-price").addClass("a-color-secondary").removeClass("a-color-price")});d("#landingItemRentalLink").attr("href","javascript:document.getElementById('rentBuySection').click();")})})})})(function(){var v=
window.AmazonUIPageJS||window.P,w=v._namespace||v.attributeErrors;return w?w("TwisterBooksDetailPageAsset"):v}(),window);
/* ******** */
(function(c){c.execute(function(){})})(function(){var c=window.AmazonUIPageJS||window.P,e=c._namespace||c.attributeErrors;return e?e("DetailPageBookProductDescriptionAssets"):c}(),window);
/* ******** */
