(function(f){var h=window.AmazonUIPageJS||window.P,p=h._namespace||h.attributeErrors,b=p?p("DetailPageEbooksAssets"):h;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,h,p){f.when("A","jQuery","ebooksImageBlockATF","cf").execute(function(b,a,c){function d(a){"undefined"!=typeof SitbReader&&SitbReader.LightboxActions.openReader(c.litbData.litbReftag)}function t(){var a=w.offset(),b=r.offset(),e=b.top-a.top,a=b.left-a.left,b=r.outerWidth(),d=r.outerHeight(),k=w.outerHeight()-
(w.outerHeight()-r.outerHeight())/2;z.css("top",e+B).css("left",a+b-z.width());q.css("position","absolute").css("top",e).css("left",a).width(b).height(d);r.css("position","absolute").css("top","0").css("left","0");l.height(k);(h.innerWidth||document.body.offsetWidth)<c.windowWidthThreshold&&g()}function g(){var a=h.innerWidth||document.body.offsetWidth;if(!(0>=a))if(a>c.windowWidthThreshold){var a=c.configWidths[1],b=a/c.holderRatio,e=c.frontImageWidth,d=c.frontImageHeight;n(a,b,e,d)}else a<c.windowWidthThreshold&&
(a=c.configWidths[0],b=a/c.holderRatio,c.frontImageAspectRatio>c.holderRatio?(e=a,d=e/c.frontImageAspectRatio):(d=b,e=d*c.frontImageAspectRatio),n(a,b,e,d))}function n(b,e,d,g){if(0<b&&0<e&&0<d&&0<g){p.length&&v.length&&(p.css("margin-left",b+c.centerColMargin).removeClass("centerColumn"),v.width(b));var k=e+c.containerMargin;m.width(b).height(k);r.width(d).height(g);q.width(d).height(g);l.height(e-(e-r.outerHeight())/2);b=(l.outerWidth()-r.outerWidth())/2;e=l.outerHeight()-r.outerHeight();q.css("top",
e).css("left",b);z.css("top",e+B).css("left",b+d-z.width());a(this).trigger("imageResize")}}var m=a("#ebooksImageBlock"),k=a("#ebooksImgBlkFront"),e=a("#ebooksImgBlockInlineVideo"),f=a("#ebooksImgBlockInlineVideoSrc");if(m.length){var w=m.find("#ebooks-img-wrapper"),l=m.find("#ebooksImageBlockContainer"),q=m.find("#ebooks-img-canvas"),r=q.find(".frontImage"),v=a("#leftCol"),p=a("#centerCol"),y=a("#ebooksImageBlockOuter"),z=y.find("#ebooksSitbLogo"),y=y.find("#ebooksSitbLogoImg"),B=parseInt(m.css("margin-top"));
t();q.addClass("image-2d");c&&c.litbData&&c.litbData.hasLitb&&c.litbData.litbReftag&&(y.removeClass("a-hidden"),y.click(d),q.click(d),q.addClass("clickableImage"));a(h).resize(g)}else throw Error("Element with id imageBlock is missing");b.on("a:image:load",function(a){e.length&&f.length&&c.hasCoverImageInlineVideo&&(k.hide(),e.show())});b.loadDynamicImage(k)});f.when("A","jQuery","imageThumbNails","ready").execute(function(b,a,c){function d(){0<e.scrollLeft()&&(B=e.scrollLeft(),B>D?E=e.scrollLeft()-
D:(E=0,setTimeout(function(){m.removeClass("enabled")},750)),g(),k.addClass("enabled"))}function t(){e.scrollLeft()+e.width()<z&&(A=z+y-(e.scrollLeft()+e.width()),A>D?E=e.scrollLeft()+D:(E=e.scrollLeft()+A,setTimeout(function(){k.removeClass("enabled")},750)),g(),m.addClass("enabled"))}function g(){e.animate({scrollLeft:E},750)}function n(){var a=h.navigator.userAgent,c=a.indexOf("MSIE "),b=a.indexOf("Trident/"),a=a.indexOf("Edge/");return 0<c||0<b||0<a}var m=a("#thumbs-left"),k=a("#thumbs-right"),
e=a(".thumbnail-container .a-carousel-viewport");b=a(".thumbnail-container .a-carousel");var f=a("#thumbImage-1"),w=a("#thumbImage-6"),l=a("#ebooksImageBlock"),q=a("#ebooksImgBlkFront"),r=a("#ebooksImgBlockInlineVideo"),p=a("#ebooksImgBlockInlineVideoSrc"),x=a(".thumbnail-container .a-carousel .a-carousel-card img"),y=6*c.thumbInlineVideos.length,z=w.width()*c.thumbInlineVideos.length;if(b.length&&e.length&&q.length&&r.length&&p.length&&l.length){var B=0,A=0,D=e.width(),E=0,C=l.find("#ebooks-img-canvas"),
G=l.find("#ebooks-img-wrapper");C.css("left","0");C.width(G.width());a(h).resize(function(){C.css("left","0");C.width(G.width())});f.addClass("selected-thumb");e.bind("mouseenter",function(){m.show(500);k.show(500);0<e.scrollLeft()&&m.addClass("enabled");e.scrollLeft()+e.width()<z&&k.addClass("enabled")});x.mouseover(function(b){var e=a(".thumbnail-container .a-carousel-card .selected-thumb"),d=a("#"+b.target.id);if(e.length&&e[0]===b.target)return!1;b=b.target.parentElement.attributes.getNamedItem("aria-posinset");
null!==b&&(b=parseInt(b.value),e.removeClass("selected-thumb"),d.addClass("selected-thumb"),q.attr("src",c.thumbImages[b-1]),r.attr("poster",c.thumbImages[b-1]),r.hide(),q.show(),p.attr("src",c.thumbInlineVideos[b-1]),r.load(),n()?setTimeout(function(){q.hide();r.show()},1E3):(q.hide(),r.show()))});m.bind("click",function(a){a.preventDefault();d()});k.bind("click",function(a){a.preventDefault();t()})}});f.when("A","jQuery","Airy","ebookVideoReady","ready").execute(function(b,a,c,d){function f(){k=
c.embed({bindings:{play:function(){d.openVideoInFullScreen&&k.enterFullScreen()}},desiredMode:"html",parentId:"ebook-airy-player-container",streamingUrls:[d.videoSource],swfUrl:d.swfUrl})}function g(){try{k.detach()}catch(a){throw Error(a.message);}k={};setTimeout(function(){f()},100)}function n(c){a.ajax("/gp/digital/fiona/ajax/reftagCall.html/ref="+(d.refTag+c),{method:"get",cache:!1});document.body.style.overflow="hidden";e.removeClass("ebook-video-overlay-hidden");k.play();setTimeout(function(){e.addClass("ebook-overlay-on");
u.addClass("ebook-overlay-on");w.addClass("ebook-overlay-on")},10)}function m(){try{k.pause()}catch(a){throw Error(a.message);}document.body.style.overflow="visible";e.removeClass("ebook-overlay-on");u.removeClass("ebook-overlay-on");w.removeClass("ebook-overlay-on");setTimeout(function(){e.addClass("ebook-video-overlay-hidden");g()},150)}var k,e=a("#ebook-video-overlay"),u=a("#ebook-lightbox"),w=a("#ebook-lightbox-video-close");b=a("#ebooksImageBlock");var l=a("#ebooks-main-image-container");if(!e.length||
"undefined"===typeof d)throw Error("Video player not found");f();a("#ebook-video-play").bind("click",function(a){a.preventDefault();n("_text")});w.bind("click",function(a){a.preventDefault();m()});a("#ebook-lightbox-dark").bind("click",function(){m()});if(b.length){var q=/Edge\/|Trident\/|MSIE /.test(h.navigator.userAgent);d.showVideoPreviewTextOnCoverImageHover&&l.length&&!q&&(l.addClass("ebookPreviewVideo"),l=document.createElement("div"),l.innerHTML=d.watchVideoText,l.setAttribute("class","ebookPreviewVideoText"),
document.getElementById("ebooks-main-image-container").appendChild(l),b.bind("click",function(a){a.preventDefault();n("_img")}))}});f.when("A","jQuery","ebooksBackgroundImageLoad","cf").execute(function(b,a,c){function d(a,c){var b=document.getElementById(a);if("undefined"!==typeof b&&null!==b){var d=b.contentDocument;"undefined"!==typeof d&&null!==d&&(b=d.body,d=d.getElementById(c),"undefined"!==typeof b&&"undefined"!=typeof d&&null!==b&&null!==d&&(b.style.background="transparent",d.allowTransparency=
"true"))}}var f=a("#a-page");f.css("background-size","100%");var g=a(".a-expander-partial-collapse-header"),n=a("#dbs-nav-section");c.displayBackgroundImage?(f.css("background-repeat","no-repeat"),d("bookDesc_iframe","iframeContent"),a(function(){d("product-description-iframe","pdIframeContent");f.css("background-image","url("+c.backgroundImageUrl+")")})):c.displayBackgroundPattern&&(f.css("background-repeat","repeat-y"),f.css("background-image","url("+c.backgroundImageUrl+")"),g.length&&(g.css("background-image",
"url("+c.backgroundImageUrl+")"),g.css("background-size",h.innerWidth+"px"),b=a("#ebooksProductDescriptionExpander"),b=(h.innerWidth-b.width())/2,g.css("background-position","-"+b+"px"),g.css("background-repeat","no-repeat")),n.length&&(n.css("background-image","url("+c.backgroundImageUrl+")"),n.css("background-size","100%")));a(h).resize(function(){c.displayBackgroundImage&&(1E3>h.innerWidth?f.css("background-size","1000px"):f.css("background-size","100%"));g.length&&g.css("background-size",h.innerWidth+
"px");n.length&&g.css("background-size",h.innerWidth+"px")})});f.when("A","jQuery","atf").execute(function(b,a){var c=a("#udpKcpAppAdImage"),d=a("#udpComiXologyAd");c.length&&b.loadHiResImage(c);d.length&&b.loadHiResImage(d)});f.when("A","jQuery","cf").execute(function(b,a){a('a[href^="#kindle-illustrated-learn-more"]').click(function(c){c.preventDefault();var b=this.hash;c=a(b).offset().top-100;a("html, body").stop().animate({scrollTop:c},1200,"swing",function(){h.location.hash=b})})});f.when("A",
"jQuery","contentQualityWidgetReady").execute(function(b,a,c){a.ajax("/gp/digital/fiona/ajax/reftagCall.html/ref="+c.onloadReftag,{method:"get",cache:!1});b.on("a:popover:show:kcqPopverPreload",function(){a.ajax("/gp/digital/fiona/ajax/reftagCall.html/ref="+c.hoverOverReftag,{method:"get",cache:!1})})});f.when("A","jQuery","ready","atf").execute(function(b,a){var c=b.state("goodreadsFacebubblesState");c!==p&&b.ajax("/kindle-dbs/external-service/goodreads-facebubbles",{method:"get",params:{profileId:c.goodreadsProfileId,
asin:c.asin},success:function(c){a("#goodreads-facebubble").append(c)}})})});