(function(f){var k=window.AmazonUIPageJS||window.P,q=k._namespace||k.attributeErrors,b=q?q("CustomerReviewsCommonAssets"):k;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,k,q){f.when("A","cr-log-utils").register("cr-ajax-model",function(b,a){function d(a){h[a]&&(h[a].abort(),delete h[a])}function e(n,f,p,r,u,m,q){var A;A=m?m:c=c++;m=A;u=u?u:f.error||function(){};r=r?r:0;p=p?p:3;var E=f.finallyCallback||function(){};q||(q="reviewsAjax"+g++,k.uet&&k.uet("tc",
q));f.params.scope=q;f.contentType="application/x-www-form-urlencoded;charset=UTF-8";var z=f.success||function(){};f.success=function(a){delete h[m];"function"===typeof z&&z(a);"function"===typeof E&&E(a)};f.error=function(c){d(m);r++;r<p?(a.logError("AJAX Post to "+n+" failed, Attempt: "+r+" out of "+p,"WARN"),e(n,f,p,r,u,m,q)):(a.logError("AJAX Post to "+n+" from "+k.location.href+" failed, exhausted "+p+" attempts","FATAL"),"function"===typeof u&&u(c),"function"===typeof E&&E(c))};h[m]=b.post(n,
f);return m}var g=0,c=1,h={};return{abort:d,post:e}});f.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,data:{REFTAG:"data-reftag",CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",UNCHECKED:"data-reviews-param-unchecked"}},events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",
FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",SEARCH_TEXTBOX:"reviews:search-textbox",SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",
MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",INPUT_PRODUCT_LINK:"reviews:input-product-link",SELECT_PRODUCT_LINK:"reviews:select-product-link",FEEDBACK_CLICK:"reviews:skyfall-feedback-click",CLIQUE_CLICK:"reviews:skyfall-clique-click"},filterOptions:{SORT_KEY:"sortBy",HELPFUL:"helpful",
RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",TWO_STAR:"two_star",THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews"},keycodes:{ENTER:13,
BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",NOWRAP:"aok-nowrap"}});f.when("A","cr-string-utils","cr-log-utils").register("cr-popup",function(b,a,d){function e(e){var c={};e&&e.data&&(c=e.data);var h=a.defaultIfBlank(c.url,e.$target.find("a").andSelf().filter("a").attr("href")),f=a.defaultIfBlank(c.title,"CustomerReviews"),f=""+f,t="";b.each({width:"500",height:"500",resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(b,d){var e=a.defaultIfBlank(c[d],b);t+=d+"="+e+","});
var t=t.slice(0,-1),p=null;try{(p=k.open(h,f,t))?p.focus():d.logError("Unable to move focus to popup window with data: "+a.stringify(c),"ERROR"),e.$event.preventDefault()}catch(q){d.logError("Unable to open window with parameters: "+a.stringify(c),"FATAL",q)}return p}b.declarative("cr-popup",["click"],d.jsGuard(e));return{popup:e}});f.when("A","ready").register("cr-global-model",function(b){var a=b.state("reviews-page-state");a||(a=b.$("#cr-state-object").data("state"));var d=null;a&&
(d=a.customerId);return{generateUrl:function(a,b){var c=a;c&&"/"!==c.charAt(c.length-1)&&(c+="/");c&&b&&(c=c+"ref="+b);return c},isSignedIn:function(){return d?!0:!1}}});f.when("A","a-expander","jQuery","reviews-constants","cr-string-utils").register("cr-global-view",function(b,a,d,e,g){function c(a){var c="";if(a&&a.closest!==q){var b=a.closest("*["+r.REFTAG+"]");b&&(c=b.attr(r.REFTAG))}g.isBlank(c)&&a&&a.closest!==q&&(a=a.closest("*[rel]"))&&(c=a.attr("rel"));return g.defaultIfBlank(c,
"cm_cr_unknown")}function h(a){return a&&"function"===typeof a.is?a.is("*["+r.getReviews.CHECKED+"]")&&a.is("*["+r.getReviews.UNCHECKED+"]"):!1}function f(a){return a&&a.has!==q&&a.is!==q?0<a.find(":checked").length||a.is(":checked"):!1}function t(a,c){return a&&a.attr!==q&&c?g.parseJSON(a.attr(c))||{}:{}}function p(a){return a!==q}var r=e.data;b.on("a:expander:review_text_read_more:toggle:collapse",function(a){p(a)&&p(a.expander)&&p(a.expander.$expander)&&1===a.expander.$expander.length&&p(a.expander.$expander[0].closest(".review"))&&
p(a.expander.$expander[0].closest(".review").offsetTop)&&(a=a.expander.$expander[0].closest(".review").offsetTop,k.scroll(0,a))});b.on("a:pageUpdate",function(){p(a)&&a.initializeExpanders()});return{getReviewsStateParamsFromElement:function(a){var c=b.reduce(r.getReviews,function(a,c){return a+"*["+c+"],"},"").slice(0,-1),d;c&&a&&a.closest!==q&&(d=a.closest(c));return h(d)?f(d)?t(d,r.getReviews.CHECKED):t(d,r.getReviews.UNCHECKED):t(d,r.getReviews.STANDARD)},getReftag:function(a){var b;a&&a.$target&&
(b=a.$target);a&&a.id&&(b=d("#"+a.id));a&&a.expander&&a.expander.$expander&&(b=a.expander.$expander);b=c(b);"cm_cr_unknown"===b&&a&&a.data&&a.data.reftag&&(b=a.data.reftag);return b},getReftagByDom:c}});f.when("A").register("cr-log-utils",function(b){function a(a,b,c){k.ueLogError&&("string"!==typeof b&&(b="FATAL"),c?k.ueLogError(c,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):k.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}
function d(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:a,jsGuard:function(b){if("function"===typeof b)return function(){try{return b.apply(this,arguments)}catch(d){a("Uncaught Error in function","FATAL",d)}};a("Unable to wrap non-function","ERROR");return b},incrementCount:function(a,b){if(k.ue){var c=d(a,b),h=k.ue.count(c)||0;k.ue.count(c,h+1)}},logCount:function(a,b,c){k.ue&&(a=d(a,c),k.ue.count(a,b))}}});f.register("cr-mash-utils",function(){var b=!1;f.when("mash").execute(function(){b=
!0});return{isMash:function(){return b}}});f.when("A","cr-log-utils").register("cr-number-utils",function(b,a){return{convertToInteger:function(b,e){if(b===parseInt(b,10))return b;if(null!==b&&b!==q&&""!==b)return parseInt(b.replace(/[^0-9]/g,""),10);if(e!==q)return e;a.logError("convertToInteger","Cannot convert "+b+" to Integer");return 0}}});f.when("A","jQuery").register("cr-streaming-utils",function(b,a){return{appendFadeIn:function(d){if(null!==d&&2<d.length&&null!==
d[1]&&null!==d[2]){var e=d[1];d=a(d[2]).hide();a(e).append(d);b.fadeIn(d,500,"ease-in-out",function(){})}}}});f.when("A","cr-log-utils").register("cr-string-utils",function(b,a){function d(a){return null===a||a===q?!0:0===b.trim(a).length}return{defaultIfBlank:function(a,b){return d(a)?b:a},isBlank:d,parseJSON:function(d){try{return b.parseJSON(d)}catch(g){a.logError("Unable to parse JSON object","ERROR",g)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===
a.indexOf(b)},stringify:function(a){return k.JSON&&k.JSON.stringify?k.JSON.stringify(a):a}}});f.when("A","cr-string-utils","3p-urijs").register("cr-uri-utils",function(b,a,d){function e(){return d(k.location.href)}function g(){return e().query()}return{getCurrentUri:e,getCurrentQueryString:g,getCurrentQueryParameters:function(){return d.parseQuery(g())},isAmazonDomain:function(c){if("string"===typeof c||c instanceof String)c=d(c);var b=a.startsWith(c.domain(),"amazon");!1===b&&(c=c.hostname(),
c=c.substring(c.indexOf(".")+1),b=a.startsWith(c,"amazon"));return b},setQueryParameters:function(c,e){if("string"===typeof c||c instanceof String)c=d(c);b.each(e,function(b,d){a.isBlank(b)?c.removeSearch(d):c=c.setSearch(d,b)});return c},setReftag:function(c,b){if("string"===typeof c||c instanceof String)c=d(c);for(var e=c.segment(),g=!1,f=e.length-1;0<=f;f--)if(a.startsWith(e[f],"ref=")){g=!0;e[f]="ref="+b;break}g||e.push("ref="+b);c.segment(e);return c}}});f.when("A","jQuery","cr-log-utils",
"cr-string-utils","afterReady").register("cr-weblab-utils",function(b,a,d,e){function g(e,g,h,m){f[g]||(d.logCount(h,0,m),e=c(a(e),g,h,m)(),k[g]=(k[g]||[]).concat(e),b.on.scroll(e))}function c(a,c,d,e){return function A(){b.onScreen(a)&&(h(c,d,e),b.each(k[c]||[],function(a){b.off("scroll",a)}));return A}}function h(a,c,e){f[a]||(f[a]=!0,b.post("/ss/customer-reviews/ajax/weblab-trigger",{params:{weblabId:a}}),d.logCount(c,1,e))}var f={},k={};b.each(a("*[data-cr-weblab-trigger-on-scroll]"),function(c,
b){var d=a(c),h=d.attr("data-cr-weblab-trigger-on-scroll"),h=e.parseJSON(h);if(null!==h){var f="cr-weblab-trigger-on-scroll-"+b;d.addClass(f);g("."+f,h.weblabId,h.metricName,h.prefix)}});return{triggerOnScrollIntoView:g,triggerWeblab:h}});f.when("A","jQuery").register("histogram-trigger",function(b){b.on.afterLoad(function(){b.onScreen(b.$("#histogramTable"))&&b.trigger("scroll")})})});